-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes/localization/

local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes", "esES") or LibStub("AceLocale-3.0"):NewLocale("HandyNotes", "esMX")
if not L then return end

L["Add Handy Note"] = "Añadir HandyNote"
L["Add this location to TomTom waypoints"] = "Añadir esta ubicación a los waypoints de TomTom"
L[ [=[
Alt+Right Click To Add a HandyNote]=] ] = [=[
Alt-click derecho para añadir un HandyNote]=]
L["|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"] = "|cFF00FF00Consejo: |cffeda55fCtrl+Mayús+clic y arrastre|cFF00FF00 para mover una nota"
L["Configuration for each individual plugin database."] = "Configuración para cada base de datos de plugin."
L["Delete Handy Note"] = "Borrar HandyNote"
L["Description/Notes:"] = "Descripción/Notas:"
L["Edit Handy Note"] = "Editar HandyNote"
L["Enable HandyNotes"] = "Activar HandyNotes"
L["Enable or disable HandyNotes"] = "Activar o desactivar HandyNotes"
L["ERROR_CREATE_NOTE1"] = "HandyNotes no puede crear una nota aquí, porque no puede encontrar su ubicación actual. Esto suele ocurrir porque no hay un mapa de la zona actual."
L["HandyNotes"] = "HandyNotes"
L["Icon Alpha"] = "Opacidad de iconos"
L["Icon Scale"] = "Escala de iconos"
L["Minimap Icon Alpha"] = "Opacidad de iconos de minimap"
L["Minimap Icon Scale"] = "Escala de iconos de minimap"
L["(No Title)"] = "(Sin titulo)"
L["Overall settings"] = "Configuración general"
L["Overall settings that affect every database"] = "Opciones que afecten a todos las bases de datos."
L["Plugin databases"] = "Bases de datos de plugins"
L["Plugins"] = "Plugins"
L["Portal"] = "Portal"
L["Show on continent map"] = "Mostrar en mapa de continente"
L["Show the following plugins on the map"] = "Mostrar los plugins seleccionados en el mapa"
L["Syntax:"] = "Sintaxis:"
L["The alpha transparency of the icons"] = "La opacidad de los iconos."
L["The overall alpha transparency of the icons on the Minimap"] = "La opacidad de los iconos en el minimapa."
L["The overall alpha transparency of the icons on the World Map"] = "La opacidad de los iconos en el mapa de mundo."
L["The overall scale of the icons on the Minimap"] = "La escala de los iconos en el minimapa."
L["The overall scale of the icons on the World Map"] = "La escala de los iconos en el mapa de mundo."
L["The scale of the icons"] = "La escala de los iconos."
L["These settings control the look and feel of HandyNotes globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."] = "Estes opciones controlan la aparanecia de HandyNotes y todos los plugins. La escala y opacidad de los iconos especificada aquí se multiplica por la escala y opacidad del plugin."
L["These settings control the look and feel of the HandyNotes icons."] = "Este opciones controlan la aparencia de los iconos de HandyNotes."
L["Title"] = "Titulo"
L["World Map Icon Alpha"] = "Opacidad de iconos de mapa"
L["World Map Icon Scale"] = "Escala de iconos de mapa"

