-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes/localization/

local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes", "frFR")
if not L then return end

L["Add Handy Note"] = "Ajouter une note pratique"
L["Add this location to TomTom waypoints"] = "Ajouter cette position aux points de naviguation de TomTom"
L[ [=[
Alt+Right Click To Add a HandyNote]=] ] = [=[
Alt+clic droit pour ajouter une note pratique]=]
L["|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"] = "|cFF00FF00Astuce : |cffeda55fCtrl+Shift+SaisirGauche|cFF00FF00 pour déplacer une note"
L["Configuration for each individual plugin database."] = "Configuration de chaque base de données des plugins individuels."
L["Delete Handy Note"] = "Supprimer une note pratique"
L["Description/Notes:"] = "Description/Notes :"
L["Edit Handy Note"] = "Éditer une note pratique"
L["Enable HandyNotes"] = "Activer HandyNotes"
L["Enable or disable HandyNotes"] = "Active ou désactive HandyNotes."
L["ERROR_CREATE_NOTE1"] = "HandyNotes ne peut pas créé de note ici car il n'arrive pas à obtenir votre position actuelle. Habituellement, cela arrive quand il n'y a pas de carte de la zone où vous vous trouvez."
L["HandyNotes"] = "HandyNotes"
L["Icon Alpha"] = "Transparence des icônes"
L["Icon Scale"] = "Échelle des icônes"
L["Minimap Icon Alpha"] = "Transp. icônes minicarte"
L["Minimap Icon Scale"] = "Échelle icônes minicarte"
L["(No Title)"] = "(Aucun titre)"
L["Overall settings"] = "Paramètres globaux"
L["Overall settings that affect every database"] = "Définit les paramètres globaux qui affectent toutes les bases de données."
L["Plugin databases"] = "Bases de données des plugins."
L["Plugins"] = "Plugins"
L["Portal"] = "Portail"
L["Show on continent map"] = "Afficher sur la carte des continents"
L["Show the following plugins on the map"] = "Montre les plugins suivants sur la carte"
L["Syntax:"] = "Syntaxe :"
L["The alpha transparency of the icons"] = "Définit la transparence des icônes."
L["The overall alpha transparency of the icons on the Minimap"] = "Définit la transparence globale des icônes de la minicarte."
L["The overall alpha transparency of the icons on the World Map"] = "Définit la transparence globale des icônes de la carte du monde."
L["The overall scale of the icons on the Minimap"] = "Définit l'échelle globale des icônes de la minicarte."
L["The overall scale of the icons on the World Map"] = "Définit l'échelle globale des icônes de la carte du monde."
L["The scale of the icons"] = "Définit l'échelle des icônes."
L["These settings control the look and feel of HandyNotes globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."] = "Ces paramètres contrôlent l'apparence globale de HandyNotes. L'échelle et la transparence des icônes définies ici sont multipliées avec l'échelle et la transparence du plugin."
L["These settings control the look and feel of the HandyNotes icons."] = "Ces paramètres contrôlent l'apparence des icônes de HandyNotes."
L["Title"] = "Titre"
L["World Map Icon Alpha"] = "Transp. icônes carte du monde"
L["World Map Icon Scale"] = "Échelle icônes carte du monde"

