-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes/localization/

local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes", "ruRU")
if not L then return end

L["Add Handy Note"] = "Добавить HandyNote"
L["Add this location to TomTom waypoints"] = "Добавить это местоположение в точки назначения TomTom"
L[ [=[
Alt+Right Click To Add a HandyNote]=] ] = "Alt+ПКМ, чтобы добавить HandyNote"
L["|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"] = "|cFF00FF00Подсказка: |cffeda55fCtrl+Shift+ЛКМ|cFF00FF00 для перемещения заметки"
L["Configuration for each individual plugin database."] = "Конфигурация баз данных модулей расширения (плагинов)"
L["Delete Handy Note"] = "Удалить HandyNote"
L["Description/Notes:"] = "Описание/заметки:"
L["Edit Handy Note"] = "Редактировать HandyNote"
L["Enable HandyNotes"] = "Включить HandyNotes"
L["Enable or disable HandyNotes"] = "Включить/выключить HandyNotes"
L["ERROR_CREATE_NOTE1"] = "HandyNotes не может создать заметку, т.к. нет возможности определить координаты текущего местоположения. Это возможно в том случае, когда у местности, в которой вы находитесь, нет карты."
L["HandyNotes"] = "HandyNotes"
L["Icon Alpha"] = "Прозрачность значка"
L["Icon Scale"] = "Масштаб значка"
L["Minimap Icon Alpha"] = "Прозрачность значка миникарты"
L["Minimap Icon Scale"] = "Масштаб значка миникарты"
L["(No Title)"] = "(без названия)"
L["Overall settings"] = "Общие настройки"
L["Overall settings that affect every database"] = "Общие установки действуют на все базы данных"
L["Plugin databases"] = "Базы данных плагинов"
L["Plugins"] = "Плагины"
L["Portal"] = "Портал"
L["Show on continent map"] = "Показывать на карте континента"
L["Show the following plugins on the map"] = "Показывать выбранные плагины на карте"
L["Syntax:"] = "Синтаксис:"
L["The alpha transparency of the icons"] = "Прозрачность значков"
L["The overall alpha transparency of the icons on the Minimap"] = "Общая прозрачность значков на миникарте"
L["The overall alpha transparency of the icons on the World Map"] = "Общая прозрачность значков на карте мира"
L["The overall scale of the icons on the Minimap"] = "Общий масштаб значков на миникарте"
L["The overall scale of the icons on the World Map"] = "Общий масштаб значков на карте мира"
L["The scale of the icons"] = "Масштаб значков"
L["These settings control the look and feel of HandyNotes globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."] = "Эти настройки контролируют вид HandyNotes. Прозрачность и масштаб значков плагинов являются производными от этих значений."
L["These settings control the look and feel of the HandyNotes icons."] = "Эти настройки контролируют вид значков HandyNotes."
L["Title"] = "Название"
L["World Map Icon Alpha"] = "Прозрачность значков карты мира"
L["World Map Icon Scale"] = "Масштаб значков карты мира"

