-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes/localization/

local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes", "deDE")
if not L then return end

L["Add Handy Note"] = "Notiz hinzufügen"
L["Add this location to TomTom waypoints"] = "Diese Stelle zu TomTom hinzufügen"
L[ [=[
Alt+Right Click To Add a HandyNote]=] ] = [=[
Alt+Rechtsklick um ein HandyNote hinzuzufügen]=]
L["|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"] = "|cFF00FF00Hinweis: |cffeda55fStrg+Shift+Linksklick|cFF00FF00 um eine Notiz zu bewegen"
L["Configuration for each individual plugin database."] = "Konfiguration für jede Plugin Datenbank."
L["Delete Handy Note"] = "Notiz löschen"
L["Description/Notes:"] = "Beschreibung/Notizen:"
L["Edit Handy Note"] = "Notiz bearbeiten"
L["Enable HandyNotes"] = "HandyNotes aktivieren"
L["Enable or disable HandyNotes"] = "HandyNotes aktivieren oder deaktivieren"
L["ERROR_CREATE_NOTE1"] = "HandyNotes konnte hier keine Notiz erstellen, da es nicht möglich ist Deine momentane Position zu ermitteln. Gewöhnlich ist dies der Fall, wenn es keine Karte für die momentane Zone gibt."
L["HandyNotes"] = "HandyNotes"
L["Icon Alpha"] = "Symboltransparenz"
L["Icon Scale"] = "Symbolgröße"
L["Minimap Icon Alpha"] = "Transparenz der Minikartensymbole"
L["Minimap Icon Scale"] = "Größe der Minikartensymbole"
L["(No Title)"] = "(Kein Titel)"
L["Overall settings"] = "Allgemeine Einstellungen"
L["Overall settings that affect every database"] = "Allgemeine Einstellungen für jede Datenbank"
L["Plugin databases"] = "Plugin Datenbanken"
L["Plugins"] = "Plugins"
L["Portal"] = "Portal"
L["Show on continent map"] = "Auf Kontinentalkarte zeigen"
L["Show the following plugins on the map"] = "Zeige die folgenden Plugins auf der Karte"
L["Syntax:"] = "Syntax:"
L["The alpha transparency of the icons"] = "Die Transparenz der Symbole"
L["The overall alpha transparency of the icons on the Minimap"] = "Die allgemeine Transparenz der Symbole auf der Minikarte."
L["The overall alpha transparency of the icons on the World Map"] = "Die allgemeine Transparenz der Symbole auf der Weltkarte."
L["The overall scale of the icons on the Minimap"] = "Die allgemeine Größe der Symbole auf der Minikarte."
L["The overall scale of the icons on the World Map"] = "Die allgemeine Größe der Symbole auf der Weltkarte."
L["The scale of the icons"] = "Die Größe der Symbole"
L["These settings control the look and feel of HandyNotes globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."] = "Diese Einstellungen legen das allgemeine Aussehen der HandyNotes fest. Die Größe und Transparenz der Symbole werden mit der Größe und Transparenz der Plugin Einstellungen multipliziert."
L["These settings control the look and feel of the HandyNotes icons."] = "Diese Einstellungen legen das Aussehen der HandyNotes Symbole fest."
L["Title"] = "Titel"
L["World Map Icon Alpha"] = "Transparenz der Weltkartensymbole"
L["World Map Icon Scale"] = "Größe der Weltkartensymbole"

