-- Pet

local BUFF = true
local DEBUFF = false
local p = Raven.ColorPalette

Raven.petSpells.HUNTER = {
	{ "Acid Spit", DEBUFF, p.Red3, cooldown = true, id = 55749 },
	{ "Ancient Hysteria", BUFF, p.Purple3, cooldown = true, id = 90355 }, -- Bloodlust/Heroism equivalent
	{ "Ankle Crack", DEBUFF, p.Brown3, cooldown = true, id = 50433 },
	{ "Bite", nil, p.Brown1, cooldown = true, id = 17253 },
	{ "Bloodthirsty", BUFF, p.Orange3, cooldown = true, id = 53186 },
	{ "Bullheaded", BUFF, p.Orange3, cooldown = true, id = 53490 },
	{ "Burrow Attack", BUFF, p.Pink, cooldown = true, id = 93433 },
	{ "Cackling Howl", BUFF, p.Brown1, cooldown = true, id = 128432 },
	{ "Carrion Feeder", nil, p.Red3, cooldown = true, id = 54044 },
	{ "Charge", BUFF, p.Brown3, cooldown = true, id = 61685 },
	{ "Claw", nil, p.Red3, cooldown = true, id = 16827 },
	{ "Clench", DEBUFF, p.Yellow3, cooldown = true, id = 50541 },
	{ "Cower", BUFF, p.Blue2, cooldown = true, id = 1742 },
	{ "Culling the Herd", BUFF, p.Brown2, id = 61680 }, 
	{ "Dash", BUFF, p.Green1, cooldown = true, id = 61684 },
	{ "Dive", BUFF, p.Purple3, cooldown = true, id = 23145 },
	{ "Demoralizing Roar", BUFF, p.Brown2, cooldown = true, id = 50256 },
	{ "Demoralizing Screech", DEBUFF, p.Brown3, cooldown = true, id = 24423 },
	{ "Dust Cloud", DEBUFF, p.Brown1, cooldown = true, id = 50285 },
	{ "Fire Breath", DEBUFF, p.Orange1, cooldown = true, id = 34889 },
	{ "Frost Breath", DEBUFF, p.Blue1, cooldown = true, id = 54644 },
	{ "Froststorm Breath", DEBUFF, p.Blue3, id = 92380 },
	{ "Furious Howl", BUFF, p.Green3, cooldown = true, id = 24604 },
	{ "Gore", DEBUFF, p.Brown3, cooldown = true, id = 35290 },
	{ "Growl", nil, p.Orange2, cooldown = true, id = 2649 },
	{ "Heart of the Phoenix", nil, p.Yellow1, cooldown = true, id = 55709 },
	{ "Horn Toss", nil, p.Brown3, cooldown = true, id = 93434 },
	{ "Lava Breath", DEBUFF, p.Yellow3, cooldown = true, id = 58604 },
	{ "Lightning Breath", DEBUFF, p.Blue1, cooldown = true, id = 24844 },
	{ "Monstrous Bite", DEBUFF, p.Brown2, cooldown = true, id = 54680 },
	{ "Nether Shock", nil, p.Purple1, cooldown = true, id = 50479 },
	{ "Owl's Focus", BUFF, p.Gray, id = 53514 },
	{ "Pin", DEBUFF, p.Blue3, cooldown = true, id = 50245 },
	{ "Prowl", BUFF, p.Gray, cooldown = true, id = 24450 },
	{ "Pummel", nil, p.Gray, cooldown = true, id = 26090 },
	{ "Qiraji Fortitude", BUFF, p.Red3, id = 90364 },
	{ "Rabid", BUFF, p.Orange2, cooldown = true, id = 53401 },
	{ "Ravage", DEBUFF, p.Brown3, cooldown = true, id = 50518 },
	{ "Rest", BUFF, p.Red2, id = 94019 },
	{ "Roar of Courage", BUFF, p.Yellow1, cooldown = true, id = 93435 },
	{ "Roar of Recovery", BUFF, p.Blue3, cooldown = true, id = 53517 },
	{ "Roar of Sacrifice", BUFF, p.Brown1, cooldown = true, id = 53480 },
	{ "Serenity Dust", nil, p.Gray, cooldown = true, id = 50318 },
	{ "Serpent's Swiftness", BUFF, p.Orange3, cooldown = true, id = 128433 },
	{ "Shell Shield", BUFF, p.Green3, cooldown = true, id = 26064 },
	{ "Smack", nil, p.Brown3, cooldown = true, id = 49966 },
	{ "Snatch", DEBUFF, p.Brown2, cooldown = true, id = 91644 },
	{ "Sonic Blast", nil, p.Brown1, cooldown = true, id = 50519 },
	{ "Spirit Beast Blessing", BUFF, p.Blue3, cooldown = true, id = 128997 },
	{ "Spirit Mend", BUFF, p.Green2, cooldown = true, id = 90361 },
	{ "Spirit Walk", BUFF, p.Gray, cooldown = true, id = 90328 },
	{ "Spore Cloud", DEBUFF, p.Brown3, cooldown = true, id = 50274 },
	{ "Stampede", DEBUFF, p.Blue2, cooldown = true, id = 57386 },
	{ "Sting", nil, p.Brown1, cooldown = true, id = 56626 },
	{ "Taunt", BUFF, p.Red3, cooldown = true, id = 53477 },
	{ "Tear Armor", DEBUFF, p.Red1, cooldown = true, id = 50498 },
	{ "Terrifying Roar", BUFF, p.Green2, cooldown = true, id = 90309 },
	{ "Thunderstomp", nil, p.Gray, cooldown = true, id = 63900 },
	{ "Time Warp", DEBUFF, p.Purple1, cooldown = true, id = 35346 },
	{ "Venom Web Spray", DEBUFF, p.Purple3, cooldown = true, id = 54706 },
	{ "Web", DEBUFF, p.Purple3, cooldown = true, id = 4167 },
	{ "Wolverine Bite", nil, p.Red3, cooldown = true, id = 53508 },
}

Raven.petSpells.WARLOCK = {
	{ "Axe Toss", BUFF, p.Orange3, cooldown = true, id = 89766 },
--	{ "Blood Pact", BUFF, p.Red3, id = 6307 }, -- removed in 5.2
	{ "Cauterize Master", BUFF, p.Orange3, cooldown = true, id = 119899 },
	{ "Devour Magic", nil, p.Purple3, cooldown = true, id = 19505 },
	{ "Felstorm", BUFF, p.Orange1, cooldown = true, id = 89751 },
	{ "Flee", BUFF, p.Red3, cooldown = true, id = 89792 },
	{ "Legion Strike", DEBUFF, p.Gray, id = 30213 },
	{ "Lesser Invisibility", BUFF, p.Blue3, id = 7870 },
	{ "Pursuit", BUFF, p.Cyan, cooldown = true, id = 30151 },
	{ "Seduction", DEBUFF, p.Brown3, id = 6358 },
	{ "Shadow Bite", nil, p.Purple2, id = 54049 },
	{ "Shadow Bulwark", BUFF, p.Purple1, cooldown = true, id = 17767 },
	{ "Shadow Shield", BUFF, p.Purple1, cooldown = true, id = 115232 },
	{ "Singe Magic", nil, p.Brown1, cooldown = true, id = 89808 },
	{ "Spell Lock", DEBUFF, p.Brown1, cooldown = true, id = 19647 },
	{ "Suffering", DEBUFF, p.Purple1, cooldown = true, id = 17735 },
	{ "Threatening Presence", BUFF, p.Purple2, id = 112042 },
	{ "Torment", nil, p.Purple3, cooldown = true, id = 3716 },
	{ "Whiplash", DEBUFF, p.Purple1, cooldown = true, id = 6360 },
}

Raven.petSpells.DEATHKNIGHT = {
	{ "Gnaw", DEBUFF, p.Red3, cooldown = true, id = 91800 },
	{ "Huddle", BUFF, p.Brown3, cooldown = true, id = 47484 },
	{ "Leap", nil, p.Purple1, cooldown = true, id = 47482 },
	{ "Monstrous Blow", DEBUFF, p.Cyan, cooldown = true, id = 91797 },
	{ "Putrid Bulwark", BUFF, p.Gray, cooldown = true, id = 91837 },
	{ "Shambling Rush", DEBUFF, p.Purple3, cooldown = true, id = 91802 },
}
