local nibRealUI = LibStub("AceAddon-3.0"):GetAddon("nibRealUI")

nibRealUI.LoadAddOnData_Raven = function()
	RavenDB = {
		["profileKeys"] = {
			["Real - Zul'jin"] = "RealUI",
		},
		["global"] = {
			["SpellLists"] = {
				["PlayerInclusions"] = {
				},
				["ClassBuffs"] = {
				},
				["PlayerDebuffExclusions"] = {
				},
				["PlayerExclusions"] = {
				},
				["TargetExclusions"] = {
				},
			},
			["FilterBuff"] = {
				["PlayerBuffs"] = {
				},
				["TargetBuffs"] = {
				},
				["PlayerBuffsExtra"] = {
				},
			},
			["DefaultCooldownColor"] = {
				["b"] = 0.2549019607843137,
				["g"] = 0.7803921568627451,
				["r"] = 0.8431372549019608,
			},
			["FilterDebuff"] = {
				["TargetDebuffs"] = {
				},
			},
			["Settings"] = {
				["WeaponEnchants"] = {
					["backdropFill"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["pointH"] = 14.99997265772085,
					["showNoDuration"] = true,
					["pointYT"] = 0.4857143463059572,
					["borderColor"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["pointX"] = 0.5,
					["pointW"] = 168.9999885429524,
					["pointXR"] = 0.3994047706772935,
					["backdropColor"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["pointY"] = 0.4999999657259233,
				},
				["Buffs"] = {
					["backdropFill"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["pointH"] = 37.00001862648837,
					["showNoDuration"] = true,
					["detectBuffsCastBy"] = "anyone",
					["timeOffset"] = 14,
					["spacingX"] = -9,
					["barHeight"] = 5,
					["anchorX"] = -3,
					["reverseSort"] = true,
					["pointYT"] = 0.001904704699695495,
					["i_iconSize"] = 30,
					["i_spacingX"] = 3,
					["detectBuffs"] = true,
					["pointW"] = 37.00001862648837,
					["hideLabel"] = true,
					["spacingY"] = -9,
					["checkDuration"] = true,
					["iconSize"] = 37,
					["checkTimeLeft"] = true,
					["filterDuration"] = 60,
					["barWidth"] = 20,
					["timeAlign"] = "LEFT",
					["i_spacingY"] = 15,
					["pointX"] = 0.9775,
					["iconAlign"] = "RIGHT",
					["borderColor"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["configuration"] = 9,
					["filterTimeLeft"] = 60,
					["maxBars"] = 40,
					["timeInset"] = 16,
					["pointXR"] = 0.00119044043730982,
					["sor"] = "T",
					["growDirection"] = false,
					["wrap"] = 20,
					["timeFormat"] = 23,
					["anchorY"] = -3,
					["backdropColor"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["iconInset"] = -15,
					["pointY"] = 0.9638,
					["hideBar"] = true,
					["iconOffset"] = 8,
				},
			},
			["DefaultPoisonColor"] = {
				["a"] = 1,
				["g"] = 0.6313725490196078,
			},
			["Defaults"] = {
				["timeMono"] = true,
				["iconFSize"] = 8,
				["spacingY"] = 1,
				["bgAlpha"] = 0,
				["iconSize"] = 22,
				["hideClock"] = true,
				["borderOffset"] = 0,
				["timeFont"] = "pixel_small",
				["labelFont"] = "pixel_small",
				["labelShadow"] = false,
				["iconFont"] = "pixel_small",
				["texture"] = "Plain",
				["borderWidth"] = 1,
				["iconMono"] = true,
				["i_iconSize"] = 35,
				["labelMono"] = true,
				["timeOutline"] = true,
				["i_spacingX"] = -9,
				["bgtexture"] = "Plain",
				["iconShadow"] = false,
				["labelFSize"] = 8,
				["i_spacingY"] = -9,
				["timeShadow"] = false,
				["labelOutline"] = true,
				["i_hideClock"] = true,
				["timeFSize"] = 8,
				["hideSpark"] = true,
				["iconOffsetX"] = -1,
				["barWidth"] = 158,
			},
			["HighlightsEnabled"] = false,
			["DefaultBuffColor"] = {
				["b"] = 0.2,
				["g"] = 0.796078431372549,
				["r"] = 0.5215686274509804,
			},
			["ButtonFacade"] = true,
			["DefaultDebuffColor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0.6470588235294118,
			},
			["DefaultMagicColor"] = {
				["a"] = 1,
				["r"] = 0.1450980392156863,
				["g"] = 0.4392156862745098,
				["b"] = 0.7176470588235294,
			},
			["Version"] = "6",
			["Minimap"] = {
				["hide"] = true,
			},
			["DefaultDiseaseColor"] = {
				["a"] = 1,
			},
			["DefaultCurseColor"] = {
				["a"] = 1,
				["r"] = 0.4196078431372549,
				["b"] = 0.6941176470588235,
			},
		},
		["profiles"] = {
			["RealUI"] = {
				["BarGroups"] = {
					["PlayerDebuffs"] = {
						["detectDebuffsCastBy"] = "anyone",
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["parentFrame"] = "oUF_RealUIPlayer_Overlay",
						["iconInset"] = 2,
						["showNoDuration"] = true,
						["name"] = "PlayerDebuffs",
						["auto"] = true,
						["pointYT"] = 0.5057142829895019,
						["i_iconSize"] = 30,
						["i_spacingX"] = 3,
						["pointW"] = 180,
						["labelInset"] = -1,
						["filterDebuffTable"] = "PlayerDebuffExclusions",
						["filterCooldownTable"] = "PlayerExclusions",
						["timeAlign"] = "LEFT",
						["i_spacingY"] = 15,
						["pointX"] = 0.1375000181652251,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["configuration"] = 8,
						["sor"] = "T",
						["pointH"] = 14.99997234344482,
						["maxBars"] = 10,
						["timeInset"] = 4,
						["pointXR"] = 0.7553571246919177,
						["wrap"] = 10,
						["timeFormat"] = 23,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["filterBuffTable"] = "PlayerExclusions",
						["detectDebuffs"] = true,
						["filterDebuffSpells"] = true,
						["pointY"] = 0.4800000290643601,
						["timeSort"] = false,
					},
					["FocusDebuffs"] = {
						["detectDebuffsCastBy"] = "anyone",
						["noPlayerDebuffs"] = true,
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["hideSpark"] = false,
						["growDirection"] = false,
						["parentFrame"] = "oUF_RealUIFocus_Overlay",
						["useDefaultFontsAndTextures"] = false,
						["showNoDuration"] = true,
						["name"] = "FocusDebuffs",
						["timeOffset"] = 14,
						["timeSort"] = false,
						["spacingX"] = -9,
						["barHeight"] = 5,
						["auto"] = true,
						["pointYT"] = 0.6009523373558408,
						["i_spacingX"] = -8,
						["pointW"] = 35.00001525878906,
						["iconOffsetX"] = 0,
						["hideLabel"] = true,
						["spacingY"] = -9,
						["iconSize"] = 35,
						["barWidth"] = 20,
						["timeAlign"] = "LEFT",
						["i_spacingY"] = -8,
						["iconAlign"] = "RIGHT",
						["pointX"] = 0.2404762086414156,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["noTargetDebuffs"] = true,
						["configuration"] = 9,
						["sor"] = "T",
						["detectDebuffsMonitor"] = "focus",
						["pointH"] = 35.00001525878906,
						["maxBars"] = 7,
						["timeInset"] = 16,
						["filterDebuffTable"] = "PlayerExclusions",
						["pointXR"] = 0.7386904489426386,
						["iconInset"] = -15,
						["wrap"] = 7,
						["timeFormat"] = 23,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["filterBuffTable"] = "PlayerExclusions",
						["detectDebuffs"] = true,
						["pointY"] = 0.3657143147786459,
						["hideBar"] = true,
						["iconOffset"] = 7,
					},
					["FocusBuffsExtra"] = {
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["mergeInto"] = "FocusBuffs",
						["detectBuffsCastBy"] = "anyone",
						["name"] = "FocusBuffsExtra",
						["minimumDuration"] = false,
						["filterBuffTypes"] = true,
						["auto"] = true,
						["pointYT"] = 2.633957635788691e-008,
						["i_iconSize"] = 30,
						["i_spacingX"] = 3,
						["detectBuffs"] = true,
						["pointW"] = 180.0000305175781,
						["detectNPCBuffs"] = true,
						["filterCooldownTable"] = "PlayerExclusions",
						["filterDuration"] = 30,
						["merged"] = true,
						["noPlayerBuffs"] = true,
						["detectStealable"] = true,
						["i_spacingY"] = 15,
						["pointX"] = 0.8928572155180432,
						["detectVehicleBuffs"] = true,
						["pointH"] = 14.99997234344482,
						["filterDebuffTable"] = "PlayerExclusions",
						["pointXR"] = -9.08261253720238e-008,
						["detectBuffsMonitor"] = "focus",
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["filterBuffTable"] = "PlayerExclusions",
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["pointY"] = 0.9857142857142858,
					},
					["ToTDebuffs"] = {
						["noPlayerDebuffs"] = true,
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["hideSpark"] = false,
						["parentFrame"] = "oUF_RealUITargetTarget_Overlay",
						["iconInset"] = -15,
						["showNoDuration"] = true,
						["name"] = "ToTDebuffs",
						["timeOffset"] = 14,
						["timeSort"] = false,
						["spacingX"] = -9,
						["auto"] = true,
						["pointYT"] = 0.5761904616582961,
						["i_spacingX"] = -8,
						["pointW"] = 35.00001525878906,
						["iconOffsetX"] = 0,
						["hideLabel"] = true,
						["detectOtherDebuffs"] = false,
						["spacingY"] = -9,
						["iconSize"] = 35,
						["barWidth"] = 20,
						["timeAlign"] = "LEFT",
						["i_spacingY"] = -8,
						["iconAlign"] = "RIGHT",
						["pointX"] = 0.7386904761904762,
						["noTargetDebuffs"] = true,
						["configuration"] = 9,
						["filterDebuffTypes"] = false,
						["sor"] = "T",
						["pointH"] = 35.00001525878906,
						["detectDebuffsMonitor"] = "targettarget",
						["maxBars"] = 7,
						["timeInset"] = 16,
						["filterDebuffTable"] = "PlayerExclusions",
						["pointXR"] = 0.2404761813935779,
						["wrap"] = 7,
						["timeFormat"] = 23,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["barHeight"] = 5,
						["filterBuffTable"] = "PlayerExclusions",
						["detectDebuffs"] = true,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["pointY"] = 0.3904761904761905,
						["hideBar"] = true,
						["noFocusDebuffs"] = false,
						["iconOffset"] = 7,
					},
					["PlayerBuffsExtra"] = {
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["mergeInto"] = "PlayerBuffs",
						["showNoDuration"] = true,
						["name"] = "PlayerBuffsExtra",
						["filterBuffList"] = {
						},
						["auto"] = true,
						["pointYT"] = 2.633957635788691e-008,
						["i_iconSize"] = 30,
						["filterBuff"] = false,
						["i_spacingX"] = 3,
						["detectBuffs"] = true,
						["pointW"] = 180.0000305175781,
						["merged"] = true,
						["i_spacingY"] = 15,
						["pointX"] = 0.8928572155180432,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["filterBuffSpells"] = true,
						["detectBuffsCastBy"] = "anyone",
						["pointH"] = 14.99997234344482,
						["pointXR"] = -9.08261253720238e-008,
						["showBuff"] = true,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["filterBuffTable"] = "PlayerInclusions",
						["pointY"] = 0.9857142857142858,
					},
					["TargetBuffs"] = {
						["desaturateFriend"] = true,
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["hideSpark"] = false,
						["parentFrame"] = "oUF_RealUITarget_Overlay",
						["iconInset"] = -15,
						["showNoDuration"] = true,
						["detectBuffsCastBy"] = "anyone",
						["name"] = "TargetBuffs",
						["timeOffset"] = 14,
						["timeSort"] = false,
						["spacingX"] = -5,
						["filterBuffList"] = {
						},
						["filterBuffTypes"] = false,
						["auto"] = true,
						["pointYT"] = 0.5190475754510788,
						["i_spacingX"] = 3,
						["detectBuffs"] = true,
						["pointW"] = 35.00001525878906,
						["iconOffsetX"] = 0,
						["hideLabel"] = true,
						["useDefaultDimensions"] = false,
						["spacingY"] = -5,
						["iconSize"] = 35,
						["filterDebuffTable"] = "PlayerExclusions",
						["playerSort"] = true,
						["filterCooldownTable"] = "PlayerExclusions",
						["timeAlign"] = "LEFT",
						["i_spacingY"] = 15,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["iconAlign"] = "RIGHT",
						["pointX"] = 0.7553571428571428,
						["barHeight"] = 5,
						["configuration"] = 9,
						["sor"] = "T",
						["filterBuffSpells"] = true,
						["detectBuffsMonitor"] = "target",
						["pointH"] = 35.00001525878906,
						["maxBars"] = 12,
						["timeInset"] = 16,
						["pointXR"] = 0.2238095147269113,
						["i_iconSize"] = 30,
						["wrap"] = 6,
						["timeFormat"] = 23,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["filterBuffTable"] = "TargetExclusions",
						["desaturate"] = true,
						["pointY"] = 0.4476190766834077,
						["hideBar"] = true,
						["barWidth"] = 20,
						["iconOffset"] = 7,
					},
					["TargetDebuffsExtra"] = {
						["detectDebuffsCastBy"] = "other",
						["detectNPCDebuffs"] = true,
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["mergeInto"] = "TargetDebuffs",
						["showNoDuration"] = true,
						["name"] = "TargetDebuffsExtra",
						["auto"] = true,
						["pointYT"] = 2.633957635788691e-008,
						["filterDebuffBars"] = true,
						["i_spacingX"] = 3,
						["pointW"] = 180.0000305175781,
						["filterDebuffBarGroup"] = "TargetDebuffs",
						["filterDebuffTable"] = "TargetExclusions",
						["merged"] = true,
						["detectDispellable"] = true,
						["i_spacingY"] = 15,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["detectInflictable"] = true,
						["pointX"] = 0.8928572155180432,
						["detectBoss"] = true,
						["filterDebuffTypes"] = true,
						["detectVehicleDebuffs"] = true,
						["pointH"] = 14.99997234344482,
						["detectDebuffsMonitor"] = "target",
						["pointXR"] = -9.08261253720238e-008,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["detectDebuffs"] = true,
						["pointY"] = 0.9857142857142858,
						["i_iconSize"] = 30,
					},
					["FocusBuffs"] = {
						["detectDebuffsCastBy"] = "anyone",
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["hideSpark"] = false,
						["pointH"] = 35.00001525878906,
						["parentFrame"] = "oUF_RealUIFocus_Overlay",
						["iconInset"] = -15,
						["name"] = "FocusBuffs",
						["timeOffset"] = 14,
						["timeSort"] = false,
						["spacingX"] = -9,
						["auto"] = true,
						["pointYT"] = 0.5761904616582961,
						["i_spacingX"] = 3,
						["detectBuffs"] = true,
						["pointW"] = 35.00001525878906,
						["iconOffsetX"] = 0,
						["hideLabel"] = true,
						["spacingY"] = -9,
						["iconSize"] = 35,
						["filterDebuffTable"] = "PlayerExclusions",
						["filterCooldownTable"] = "PlayerExclusions",
						["noPlayerBuffs"] = true,
						["barWidth"] = 20,
						["timeAlign"] = "LEFT",
						["i_spacingY"] = 15,
						["iconAlign"] = "RIGHT",
						["pointX"] = 0.2404762086414156,
						["configuration"] = 9,
						["filterDebuffTypes"] = true,
						["detectBuffsMonitor"] = "focus",
						["i_iconSize"] = 30,
						["sor"] = "T",
						["growDirection"] = false,
						["detectDebuffsMonitor"] = "focus",
						["maxBars"] = 7,
						["timeInset"] = 16,
						["pointXR"] = 0.7386904489426386,
						["wrap"] = 7,
						["timeFormat"] = 23,
						["desaturateFriend"] = true,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["barHeight"] = 5,
						["filterBuffTable"] = "PlayerExclusions",
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["desaturate"] = true,
						["noTargetBuffs"] = false,
						["pointY"] = 0.3904761904761905,
						["hideBar"] = true,
						["iconOffset"] = 7,
					},
					["PlayerBuffs"] = {
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["hideSpark"] = false,
						["growDirection"] = false,
						["parentFrame"] = "oUF_RealUIPlayer_Overlay",
						["name"] = "PlayerBuffs",
						["timeOffset"] = 14,
						["timeSort"] = false,
						["spacingX"] = -5,
						["anchorX"] = -63,
						["minimumDuration"] = false,
						["filterBuffList"] = {
						},
						["auto"] = true,
						["pointYT"] = 0.5190475754510788,
						["i_spacingX"] = 2,
						["detectBuffs"] = true,
						["pointW"] = 34.99998474121094,
						["iconOffsetX"] = 0,
						["anchorPoint"] = "LEFT",
						["hideLabel"] = true,
						["useDefaultDimensions"] = false,
						["spacingY"] = -5,
						["checkDuration"] = true,
						["iconSize"] = 35,
						["filterDebuffTable"] = "PlayerExclusions",
						["playerSort"] = true,
						["checkTimeLeft"] = true,
						["i_hideClock"] = false,
						["filterDuration"] = 67,
						["barWidth"] = 20,
						["timeAlign"] = "LEFT",
						["i_spacingY"] = 15,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["iconAlign"] = "RIGHT",
						["pointX"] = 0.223809560139974,
						["desaturate"] = true,
						["configuration"] = 9,
						["minimumTimeLeft"] = false,
						["sor"] = "T",
						["i_iconSize"] = 25,
						["filterTimeLeft"] = 67,
						["pointH"] = 35.00001525878906,
						["maxBars"] = 12,
						["timeInset"] = 16,
						["pointXR"] = 0.7553571156093053,
						["iconInset"] = -15,
						["detectBuffsCastBy"] = "anyone",
						["wrap"] = 6,
						["timeFormat"] = 23,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["barHeight"] = 5,
						["filterBuffTable"] = "PlayerExclusions",
						["pointY"] = 0.4476190766834077,
						["hideBar"] = true,
						["filterBuffSpells"] = true,
						["iconOffset"] = 7,
					},
					["Buffs"] = {
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["hideSpark"] = false,
						["pointH"] = 35.99995803833008,
						["iconInset"] = -15,
						["showNoDuration"] = true,
						["name"] = "Buffs",
						["timeOffset"] = 14,
						["timeSort"] = false,
						["spacingX"] = -9,
						["auto"] = true,
						["reverseSort"] = true,
						["pointYT"] = -0.003809600103469122,
						["i_spacingX"] = 3,
						["detectBuffs"] = true,
						["pointW"] = 35.99995803833008,
						["iconOffsetX"] = 0,
						["anchorPoint"] = "TOPRIGHT",
						["hideLabel"] = true,
						["useDefaultDimensions"] = false,
						["spacingY"] = -9,
						["checkDuration"] = true,
						["iconSize"] = 36,
						["filterDebuffTable"] = "PlayerDebuffExclusions",
						["checkTimeLeft"] = true,
						["filterDuration"] = 60,
						["barWidth"] = 20,
						["timeAlign"] = "LEFT",
						["i_spacingY"] = 15,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["iconAlign"] = "RIGHT",
						["pointX"] = 0.9809523809523809,
						["configuration"] = 9,
						["sor"] = "T",
						["i_iconSize"] = 30,
						["filterTimeLeft"] = 60,
						["growDirection"] = false,
						["anchorFrame"] = "RealUIPositionersBuffs",
						["maxBars"] = 40,
						["timeInset"] = 16,
						["pointXR"] = -0.002380927403767904,
						["detectBuffsCastBy"] = "anyone",
						["wrap"] = 20,
						["timeFormat"] = 23,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["barHeight"] = 5,
						["filterBuffTable"] = "PlayerExclusions",
						["pointY"] = 0.96952392578125,
						["hideBar"] = true,
						["iconOffset"] = 7,
					},
					["ToTDebuffsExtra"] = {
						["detectDebuffsCastBy"] = "anyone",
						["detectNPCDebuffs"] = true,
						["noPlayerDebuffs"] = true,
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["showNoDuration"] = true,
						["name"] = "ToTDebuffsExtra",
						["auto"] = true,
						["pointYT"] = 2.633957635788691e-008,
						["i_spacingX"] = -8,
						["pointW"] = 180.0000305175781,
						["filterDebuffTable"] = "PlayerExclusions",
						["merged"] = true,
						["detectDispellable"] = true,
						["i_spacingY"] = -8,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["detectInflictable"] = true,
						["pointX"] = 0.8928572155180432,
						["noTargetDebuffs"] = true,
						["detectBoss"] = true,
						["detectVehicleDebuffs"] = true,
						["pointH"] = 14.99997234344482,
						["detectDebuffsMonitor"] = "targettarget",
						["mergeInto"] = "ToTDebuffs",
						["pointXR"] = -9.08261253720238e-008,
						["filterDebuffTypes"] = true,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["filterBuffTable"] = "PlayerExclusions",
						["detectDebuffs"] = true,
						["pointY"] = 0.9857142857142858,
					},
					["TargetDebuffs"] = {
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["parentFrame"] = "oUF_RealUITarget_Overlay",
						["iconInset"] = 2,
						["showNoDuration"] = true,
						["name"] = "TargetDebuffs",
						["barColors"] = "Standard",
						["auto"] = true,
						["pointYT"] = 0.5057142829895019,
						["i_iconSize"] = 30,
						["i_spacingX"] = 3,
						["pointW"] = 180.0000305175781,
						["labelInset"] = 3,
						["detectOtherDebuffs"] = false,
						["iconColors"] = "Normal",
						["filterDebuffTable"] = "TargetExclusions",
						["filterDebuffList"] = {
						},
						["timeAlign"] = "RIGHT",
						["i_spacingY"] = 15,
						["pointX"] = 0.7559523082914806,
						["desaturate"] = true,
						["filterDebuffTypes"] = false,
						["sor"] = "T",
						["detectDebuffsMonitor"] = "target",
						["pointH"] = 14.99997234344482,
						["maxBars"] = 8,
						["pointXR"] = 0.1369048164004371,
						["wrap"] = 10,
						["timeFormat"] = 23,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["filterBuffTable"] = "PlayerExclusions",
						["detectDebuffs"] = true,
						["filterDebuffSpells"] = true,
						["pointY"] = 0.4800000290643601,
						["timeSort"] = false,
					},
				},
				["Durations"] = {
					["Cloak of Shadows"] = 5,
					["Deadly Poison"] = 3600.022,
					["Blade Twisting"] = 8,
					["Earthbind"] = 5,
					["Slice and Dice"] = 27,
					["Rupture"] = 12,
					["Combat Readiness"] = 20,
					["Dancing Steel"] = 12,
					["Vendetta"] = 20,
					["Drink"] = 20,
					["Food"] = 20,
					["Anticipation"] = 15,
					["Windswept Pages"] = 20,
					["Garrote"] = 18,
					["Blind"] = 60,
					["Tricks of the Trade"] = 6,
					["Recuperate"] = 24,
					["Weakened Soul"] = 15,
					["Jade Spirit"] = 12,
					["Moderate Insight"] = 15,
					["Arcane Missiles!"] = 20,
					["Sprint"] = 8,
					["Honorless Target"] = 30,
					["Hand of Protection"] = 10,
					["Resurrection Sickness"] = 600,
					["Deep Insight"] = 15,
					["Frostbolt"] = 9,
					["Revealing Strike"] = 15,
					["Paralytic Poison"] = 15,
					["Leeching Poison"] = 3600.022,
					["Shallow Insight"] = 15,
					["Grace"] = 15,
					["Recently Bandaged"] = 60,
					["Hurricane"] = 12,
					["Vanish"] = 3,
					["Eye of Vengeance"] = 10,
					["Arrow of Time"] = 20,
					["Harmony"] = 20,
					["River's Song"] = 7,
					["Blindside"] = 10,
					["Deserter"] = 900,
					["Kidney Shot"] = 2,
					["Enlightenment"] = 10,
					["First Aid"] = 8,
					["Plague of Ages"] = 9,
					["Adrenaline Rush"] = 20,
					["Killing Spree"] = 2,
					["Power Word: Shield"] = 15,
					["Forbearance"] = 60,
					["Paralysis"] = 4,
					["Rejuvenation"] = 12.597,
					["Cheap Shot"] = 4,
					["Evasion"] = 15,
				},
				["muteSFX"] = true,
				["Conditions"] = {
					["HUNTER"] = {
						["Check Aspect!"] = {
							["tests"] = {
								["Player Status"] = {
									["levelOffHand"] = 1,
									["minShards"] = 1,
									["levelMainHand"] = 1,
									["minEclipsePower"] = 0,
									["minHolyPower"] = 1,
									["minHealth"] = 100,
									["minComboPoints"] = 5,
									["levelRanged"] = 1,
									["minPower"] = 100,
									["level"] = 80,
								},
							},
							["result"] = false,
							["testResult"] = false,
						},
						["Aspect Missing"] = {
							["tests"] = {
								["Player Status"] = {
									["levelOffHand"] = 1,
									["minShards"] = 1,
									["levelMainHand"] = 1,
									["minEclipsePower"] = 0,
									["minHolyPower"] = 1,
									["minHealth"] = 100,
									["minComboPoints"] = 5,
									["levelRanged"] = 1,
									["minPower"] = 100,
									["level"] = 80,
								},
								["Spell Ready"] = {
									["notUsable"] = false,
									["gcd"] = false,
								},
							},
							["result"] = false,
							["testResult"] = false,
						},
						["No Pet!"] = {
							["tests"] = {
								["Player Status"] = {
									["levelOffHand"] = 1,
									["minShards"] = 1,
									["levelMainHand"] = 1,
									["minEclipsePower"] = 0,
									["minHolyPower"] = 1,
									["minHealth"] = 100,
									["minComboPoints"] = 5,
									["levelRanged"] = 1,
									["minPower"] = 100,
									["level"] = 80,
								},
							},
							["result"] = false,
							["testResult"] = false,
						},
						["Trueshot Aura Missing"] = {
							["tests"] = {
								["Player Status"] = {
									["levelOffHand"] = 1,
									["minShards"] = 1,
									["levelMainHand"] = 1,
									["minEclipsePower"] = 0,
									["minHolyPower"] = 1,
									["minHealth"] = 100,
									["minComboPoints"] = 5,
									["levelRanged"] = 1,
									["minPower"] = 100,
									["level"] = 80,
								},
								["Spell Ready"] = {
									["notUsable"] = false,
									["gcd"] = false,
								},
							},
							["result"] = false,
							["testResult"] = false,
						},
					},
					["SHAMAN"] = {
						["Cleanse Spirit (Magic)"] = {
							["tests"] = {
								["Debuff Type"] = {
									["toggle"] = false,
								},
								["Spell Ready"] = {
									["notUsable"] = false,
									["gcd"] = false,
								},
								["Player Status"] = {
									["levelOffHand"] = 1,
									["minShards"] = 1,
									["levelMainHand"] = 1,
									["minEclipsePower"] = 0,
									["minHolyPower"] = 1,
									["minHealth"] = 100,
									["minComboPoints"] = 5,
									["level"] = 80,
									["minPower"] = 100,
									["levelRanged"] = 1,
								},
							},
							["result"] = false,
							["testResult"] = false,
						},
						["Cleanse Spirit (Curse)"] = {
							["tests"] = {
								["Debuff Type"] = {
									["toggle"] = false,
								},
								["Spell Ready"] = {
									["notUsable"] = false,
									["gcd"] = false,
								},
							},
							["result"] = false,
							["testResult"] = false,
						},
						["Shield Missing"] = {
							["tests"] = {
								["Player Status"] = {
									["levelOffHand"] = 1,
									["minShards"] = 1,
									["levelMainHand"] = 1,
									["minEclipsePower"] = 0,
									["minHolyPower"] = 1,
									["minHealth"] = 100,
									["minComboPoints"] = 5,
									["level"] = 80,
									["minPower"] = 100,
									["levelRanged"] = 1,
								},
								["Spell Ready"] = {
									["notUsable"] = false,
									["gcd"] = false,
								},
							},
							["result"] = false,
							["testResult"] = false,
						},
						["Weapon Buff Missing"] = {
							["tests"] = {
								["Player Status"] = {
									["levelOffHand"] = 1,
									["minShards"] = 1,
									["levelMainHand"] = 1,
									["minEclipsePower"] = 0,
									["minHolyPower"] = 1,
									["minHealth"] = 100,
									["minComboPoints"] = 5,
									["level"] = 80,
									["minPower"] = 100,
									["levelRanged"] = 1,
								},
								["Spell Ready"] = {
									["notUsable"] = false,
									["gcd"] = false,
								},
							},
							["result"] = false,
							["testResult"] = false,
						},
					},
					["ROGUE"] = {
						["Lethal Poison Missing"] = {
							["tests"] = {
								["Player Status"] = {
									["isMounted"] = 0,
									["checkLevel"] = true,
									["inArena"] = true,
									["inInstance"] = true,
									["inGroup"] = true,
									["inBattleground"] = true,
									["inCombat"] = 0,
								},
							},
							["associatedSpell"] = "#2823",
						},
						["Non-Lethal Poison Missing"] = {
							["tests"] = {
								["Player Status"] = {
									["isMounted"] = 0,
									["checkLevel"] = true,
									["inArena"] = true,
									["inInstance"] = true,
									["inGroup"] = true,
									["inBattleground"] = true,
								},
							},
							["associatedSpell"] = "#5761",
						},
					},
				},
			},
		},
	}
end