local _, private = ...

private.AddOns.Raven = function()
	_G.RavenDB = {
		["profileKeys"] = {
		},
		["global"] = {
			["SpellLists"] = {
				["PlayerInclusions"] = {
				},
				["ClassBuffs"] = {
				},
				["PlayerDebuffExclusions"] = {
				},
				["PlayerExclusions"] = {
				},
				["TargetExclusions"] = {
				},
			},
			["FilterBuff"] = {
				["PlayerBuffs"] = {
				},
				["TargetBuffs"] = {
				},
				["PlayerBuffsExtra"] = {
				},
			},
			["DefaultCooldownColor"] = {
				["b"] = 0.2549019607843137,
				["g"] = 0.7803921568627451,
				["r"] = 0.8431372549019608,
			},
			["FilterDebuff"] = {
				["TargetDebuffs"] = {
				},
			},
			["Settings"] = {
				["WeaponEnchants"] = {
					["backdropFill"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["pointH"] = 14.99997265772085,
					["showNoDuration"] = true,
					["pointYT"] = 0.4857143463059572,
					["borderColor"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["pointX"] = 0.5,
					["pointW"] = 168.9999885429524,
					["pointXR"] = 0.3994047706772935,
					["backdropColor"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["pointY"] = 0.4999999657259233,
				},
				["Buffs"] = {
					["backdropFill"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["pointH"] = 37.00001862648837,
					["showNoDuration"] = true,
					["detectBuffsCastBy"] = "anyone",
					["timeOffset"] = 14,
					["spacingX"] = -9,
					["barHeight"] = 5,
					["anchorX"] = -3,
					["reverseSort"] = true,
					["pointYT"] = 0.001904704699695495,
					["i_iconSize"] = 30,
					["i_spacingX"] = 3,
					["detectBuffs"] = true,
					["pointW"] = 37.00001862648837,
					["hideLabel"] = true,
					["spacingY"] = -9,
					["checkDuration"] = true,
					["iconSize"] = 37,
					["checkTimeLeft"] = true,
					["filterDuration"] = 60,
					["barWidth"] = 20,
					["timeAlign"] = "LEFT",
					["i_spacingY"] = 15,
					["pointX"] = 0.9775,
					["iconAlign"] = "RIGHT",
					["borderColor"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["configuration"] = 9,
					["filterTimeLeft"] = 60,
					["maxBars"] = 40,
					["timeInset"] = 16,
					["pointXR"] = 0.00119044043730982,
					["sor"] = "T",
					["growDirection"] = false,
					["wrap"] = 20,
					["timeFormat"] = 23,
					["anchorY"] = -3,
					["backdropColor"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["iconInset"] = -15,
					["pointY"] = 0.9638,
					["hideBar"] = true,
					["iconOffset"] = 8,
				},
			},
			["DefaultPoisonColor"] = {
				["a"] = 1,
				["g"] = 0.6313725490196078,
			},
			["Defaults"] = {
				["barHeight"] = 18,
				["iconFSize"] = 14,
				["bgAlpha"] = 0,
				["hideSpark"] = true,
				["backdropInset"] = 4.01,
				["iconSize"] = 24,
				["hideClock"] = true,
				["borderOffset"] = 0,
				["timeFont"] = "Roboto Condensed",
				["borderWidth"] = 1,
				["iconFont"] = "Roboto Condensed",
				["barWidth"] = 158,
				["labelFont"] = "Roboto",
				["spacingY"] = 1,
				["i_barHeight"] = 1,
				["i_barWidth"] = 5,
				["i_hideClock"] = true,
				["i_iconSize"] = 36,
				["i_spacingX"] = -9,
				["texture"] = "Plain",
				["bgtexture"] = "Plain",
				["labelFSize"] = 12,
				["i_spacingY"] = -9,
				["timeFSize"] = 14,
				["iconOutline"] = false,
			},
			["HighlightsEnabled"] = false,
			["DefaultBuffColor"] = {
				["b"] = 0.2,
				["g"] = 0.796078431372549,
				["r"] = 0.5215686274509804,
			},
			["ButtonFacade"] = true,
			["DefaultDebuffColor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0.6470588235294118,
			},
			["DefaultMagicColor"] = {
				["a"] = 1,
				["r"] = 0.1450980392156863,
				["g"] = 0.4392156862745098,
				["b"] = 0.7176470588235294,
			},
			["Version"] = "7",
			["Minimap"] = {
				["hide"] = true,
			},
			["DefaultDiseaseColor"] = {
				["a"] = 1,
			},
			["DefaultCurseColor"] = {
				["a"] = 1,
				["r"] = 0.4196078431372549,
				["b"] = 0.6941176470588235,
			},
		},
		["profiles"] = {
			["RealUI"] = {
				["BarGroups"] = {
					["PlayerDebuffs"] = {
						["detectDebuffsCastBy"] = "anyone",
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["parentFrame"] = "oUF_RealUIPlayer_Overlay",
						["i_barHeight"] = 5,
						["name"] = "PlayerDebuffs",
						["timeSort"] = false,
						["auto"] = true,
						["pointYT"] = 0.47500001366933,
						["i_spacingX"] = 3,
						["pointW"] = 182.000015258789,
						["labelInset"] = 3,
						["filterDebuffTable"] = "PlayerDebuffExclusions",
						["filterCooldownTable"] = "PlayerExclusions",
						["filterDebuffSpells"] = true,
						["bars"] = {
						},
						["timeAlign"] = "LEFT",
						["i_spacingY"] = 15,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["i_barWidth"] = 20,
						["pointX"] = 0.0968749938408538,
						["configuration"] = 8,
						["sor"] = "T",
						["maxBars"] = 10,
						["pointH"] = 17.9999866485596,
						["pointXR"] = 0.808333337571886,
						["wrap"] = 10,
						["timeFormat"] = 23,
						["showNoDuration"] = true,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["i_iconSize"] = 30,
						["filterBuffTable"] = "PlayerExclusions",
						["detectDebuffs"] = true,
						["pointY"] = 0.509999998982748,
					},
					["TargetDebuffs"] = {
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["parentFrame"] = "oUF_RealUITarget_Overlay",
						["i_barHeight"] = 5,
						["name"] = "TargetDebuffs",
						["barColors"] = "Standard",
						["auto"] = true,
						["pointYT"] = 0.47500001366933,
						["i_spacingX"] = 3,
						["pointW"] = 182.000030517578,
						["labelInset"] = 3,
						["detectOtherDebuffs"] = false,
						["iconColors"] = "Normal",
						["filterDebuffTable"] = "ClassBuffs",
						["filterDebuffList"] = {
						},
						["filterCooldownTable"] = "ClassBuffs",
						["filterDebuffSpells"] = true,
						["desaturate"] = true,
						["bars"] = {
						},
						["timeAlign"] = "RIGHT",
						["i_spacingY"] = 15,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["i_barWidth"] = 20,
						["pointX"] = 0.808854115241107,
						["filterDebuffTypes"] = false,
						["detectDebuffsMonitor"] = "target",
						["maxBars"] = 8,
						["sor"] = "T",
						["pointH"] = 17.9999866485596,
						["pointXR"] = 0.0963542082243469,
						["wrap"] = 10,
						["timeFormat"] = 23,
						["showNoDuration"] = true,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["filterBuffTable"] = "ClassBuffs",
						["detectDebuffs"] = true,
						["timeSort"] = false,
						["pointY"] = 0.509999998982748,
						["i_iconSize"] = 30,
					},
					["FocusBuffs"] = {
						["detectDebuffsCastBy"] = "anyone",
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["hideSpark"] = false,
						["growDirection"] = false,
						["parentFrame"] = "oUF_RealUIFocus_Overlay",
						["iconInset"] = -18,
						["i_barHeight"] = 5,
						["name"] = "FocusBuffs",
						["timeOffset"] = 18,
						["timeSort"] = false,
						["spacingX"] = -9,
						["auto"] = true,
						["pointYT"] = 0.559166654290095,
						["i_spacingX"] = 3,
						["detectBuffs"] = true,
						["pointW"] = 36.0000076293945,
						["hideLabel"] = true,
						["spacingY"] = -9,
						["iconSize"] = 36,
						["filterCooldownTable"] = "PlayerExclusions",
						["desaturate"] = true,
						["i_barWidth"] = 20,
						["noPlayerBuffs"] = true,
						["bars"] = {
						},
						["barWidth"] = 5,
						["timeAlign"] = "LEFT",
						["detectBuffsMonitor"] = "focus",
						["i_spacingY"] = 15,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["iconAlign"] = "RIGHT",
						["pointX"] = 0.19218750367562,
						["desaturateFriend"] = true,
						["configuration"] = 9,
						["filterDebuffTable"] = "PlayerExclusions",
						["filterDebuffTypes"] = true,
						["detectDebuffsMonitor"] = "focus",
						["sor"] = "T",
						["maxBars"] = 7,
						["timeInset"] = 16,
						["pointH"] = 36.0000076293945,
						["pointXR"] = 0.789062493542831,
						["wrap"] = 7,
						["timeFormat"] = 23,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["filterBuffTable"] = "PlayerExclusions",
						["barHeight"] = 1,
						["noTargetBuffs"] = false,
						["pointY"] = 0.410833342403835,
						["i_iconSize"] = 30,
						["hideBar"] = true,
						["iconOffset"] = 5,
					},
					["FocusDebuffs"] = {
						["detectDebuffsCastBy"] = "anyone",
						["noTargetDebuffs"] = true,
						["noPlayerDebuffs"] = true,
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["hideSpark"] = false,
						["pointH"] = 36.0000076293945,
						["parentFrame"] = "oUF_RealUIFocus_Overlay",
						["iconInset"] = -18,
						["showNoDuration"] = true,
						["i_barHeight"] = 5,
						["name"] = "FocusDebuffs",
						["timeOffset"] = 18,
						["timeSort"] = false,
						["spacingX"] = -9,
						["auto"] = true,
						["pointYT"] = 0.580833318752714,
						["i_iconSize"] = 35,
						["i_spacingX"] = -8,
						["pointW"] = 36.0000076293945,
						["hideLabel"] = true,
						["spacingY"] = -9,
						["iconSize"] = 36,
						["barWidth"] = 5,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["barHeight"] = 1,
						["bars"] = {
						},
						["timeAlign"] = "LEFT",
						["i_spacingY"] = -8,
						["iconAlign"] = "RIGHT",
						["pointX"] = 0.19218750367562,
						["filterDebuffTable"] = "PlayerExclusions",
						["configuration"] = 9,
						["detectDebuffsMonitor"] = "focus",
						["sor"] = "T",
						["maxBars"] = 7,
						["timeInset"] = 16,
						["growDirection"] = false,
						["pointXR"] = 0.789062493542831,
						["wrap"] = 7,
						["timeFormat"] = 23,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["filterBuffTable"] = "PlayerExclusions",
						["detectDebuffs"] = true,
						["i_barWidth"] = 20,
						["pointY"] = 0.389166677941215,
						["hideBar"] = true,
						["iconOffset"] = 5,
					},
					["PlayerBuffs"] = {
						["filterBuffSpells"] = true,
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["hideSpark"] = false,
						["pointH"] = 35.9999732971191,
						["iconInset"] = -18,
						["i_barHeight"] = 5,
						["name"] = "PlayerBuffs",
						["timeOffset"] = 18,
						["timeSort"] = false,
						["spacingX"] = -9,
						["anchorX"] = -63,
						["minimumDuration"] = false,
						["filterBuffList"] = {
						},
						["auto"] = true,
						["pointYT"] = 0.490000023269651,
						["i_spacingX"] = 2,
						["detectBuffs"] = true,
						["pointW"] = 36.0000076293945,
						["anchorPoint"] = "LEFT",
						["hideLabel"] = true,
						["spacingY"] = -9,
						["iconSize"] = 36,
						["filterDebuffTable"] = "PlayerExclusions",
						["playerSort"] = true,
						["checkTimeLeft"] = true,
						["i_hideClock"] = false,
						["filterCooldownTable"] = "ClassBuffs",
						["filterDuration"] = 60,
						["i_barWidth"] = 20,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["bars"] = {
						},
						["barWidth"] = 5,
						["timeAlign"] = "LEFT",
						["i_spacingY"] = 15,
						["iconAlign"] = "RIGHT",
						["detectBuffsCastBy"] = "anyone",
						["pointX"] = 0.172916671567493,
						["desaturate"] = true,
						["growDirection"] = false,
						["configuration"] = 9,
						["minimumTimeLeft"] = false,
						["filterTimeLeft"] = 60,
						["sor"] = "T",
						["maxBars"] = 12,
						["timeInset"] = 16,
						["pointXR"] = 0.808333325650957,
						["wrap"] = 6,
						["timeFormat"] = 23,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["i_iconSize"] = 25,
						["filterBuffTable"] = "PlayerExclusions",
						["barHeight"] = 1,
						["pointY"] = 0.480000002034505,
						["hideBar"] = true,
						["iconOffset"] = 5,
					},
					["Buffs"] = {
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["hideSpark"] = false,
						["growDirection"] = false,
						["iconInset"] = -18,
						["showNoDuration"] = true,
						["detectBuffsCastBy"] = "anyone",
						["name"] = "Buffs",
						["timeOffset"] = 18,
						["timeSort"] = false,
						["spacingX"] = -9,
						["barHeight"] = 1,
						["auto"] = true,
						["reverseSort"] = true,
						["pointYT"] = 0.000833355500960744,
						["i_spacingX"] = 3,
						["detectBuffs"] = true,
						["pointW"] = 35.9999732971191,
						["anchorPoint"] = "TOPRIGHT",
						["hideLabel"] = true,
						["spacingY"] = -9,
						["iconSize"] = 36,
						["filterCooldownTable"] = "ClassBuffs",
						["filterDuration"] = 60,
						["i_barWidth"] = 20,
						["i_iconSize"] = 30,
						["bars"] = {
						},
						["barWidth"] = 5,
						["timeAlign"] = "LEFT",
						["i_spacingY"] = 15,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["iconAlign"] = "RIGHT",
						["pointX"] = 0.980729231470157,
						["configuration"] = 9,
						["filterDebuffTable"] = "ClassBuffs",
						["filterTimeLeft"] = 60,
						["sor"] = "T",
						["maxBars"] = 40,
						["timeInset"] = 16,
						["pointH"] = 35.9999732971191,
						["pointXR"] = 0.000520783629685489,
						["wrap"] = 20,
						["timeFormat"] = 23,
						["i_barHeight"] = 5,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["filterBuffTable"] = "ClassBuffs",
						["pointY"] = 0.969166669803195,
						["anchorFrame"] = "RealUIPositionersBuffs",
						["hideBar"] = true,
						["iconOffset"] = 5,
					},
					["TargetBuffs"] = {
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["hideSpark"] = false,
						["parentFrame"] = "oUF_RealUITarget_Overlay",
						["iconInset"] = -18,
						["detectBuffsCastBy"] = "anyone",
						["i_barHeight"] = 5,
						["name"] = "TargetBuffs",
						["timeOffset"] = 18,
						["timeSort"] = false,
						["spacingX"] = -9,
						["filterBuffList"] = {
						},
						["filterBuffTypes"] = false,
						["auto"] = true,
						["pointYT"] = 0.490000023269651,
						["i_spacingX"] = 3,
						["detectBuffs"] = true,
						["pointW"] = 35.9999732971191,
						["hideLabel"] = true,
						["spacingY"] = -9,
						["iconSize"] = 36,
						["filterDebuffTable"] = "PlayerExclusions",
						["playerSort"] = true,
						["filterCooldownTable"] = "ClassBuffs",
						["desaturate"] = true,
						["bars"] = {
						},
						["barWidth"] = 5,
						["timeAlign"] = "LEFT",
						["i_spacingY"] = 15,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["iconAlign"] = "RIGHT",
						["i_barWidth"] = 20,
						["pointX"] = 0.808333345519171,
						["filterBuffSpells"] = true,
						["desaturateFriend"] = true,
						["configuration"] = 9,
						["sor"] = "T",
						["maxBars"] = 12,
						["timeInset"] = 16,
						["pointH"] = 35.9999732971191,
						["pointXR"] = 0.172916669580671,
						["wrap"] = 6,
						["timeFormat"] = 23,
						["showNoDuration"] = true,
						["detectBuffsMonitor"] = "target",
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["filterBuffTable"] = "ClassBuffs",
						["barHeight"] = 1,
						["pointY"] = 0.480000002034505,
						["i_iconSize"] = 30,
						["hideBar"] = true,
						["iconOffset"] = 5,
					},
					["ToTDebuffs"] = {
						["noTargetDebuffs"] = true,
						["noPlayerDebuffs"] = true,
						["backdropFill"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["hideSpark"] = false,
						["parentFrame"] = "oUF_RealUITargetTarget_Overlay",
						["iconInset"] = -18,
						["i_barHeight"] = 5,
						["name"] = "ToTDebuffs",
						["timeOffset"] = 18,
						["spacingX"] = -9,
						["barHeight"] = 1,
						["auto"] = true,
						["pointYT"] = 0.559166654290095,
						["i_spacingX"] = -8,
						["pointW"] = 35.9999732971191,
						["hideLabel"] = true,
						["detectOtherDebuffs"] = false,
						["spacingY"] = -9,
						["iconSize"] = 36,
						["filterDebuffTable"] = "PlayerExclusions",
						["i_iconSize"] = 35,
						["i_barWidth"] = 20,
						["timeSort"] = false,
						["bars"] = {
						},
						["timeAlign"] = "LEFT",
						["i_spacingY"] = -8,
						["borderColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["iconAlign"] = "RIGHT",
						["pointX"] = 0.789062513411044,
						["noFocusDebuffs"] = false,
						["sor"] = "T",
						["configuration"] = 9,
						["filterDebuffTypes"] = false,
						["detectDebuffsMonitor"] = "targettarget",
						["maxBars"] = 7,
						["timeInset"] = 16,
						["pointH"] = 36.0000076293945,
						["pointXR"] = 0.192187501688798,
						["wrap"] = 7,
						["timeFormat"] = 23,
						["showNoDuration"] = true,
						["barWidth"] = 5,
						["backdropColor"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["filterBuffTable"] = "PlayerExclusions",
						["detectDebuffs"] = true,
						["pointY"] = 0.410833342403835,
						["hideBar"] = true,
						["iconOffset"] = 5,
					},
				},
				["Durations"] = {
					["Cloak of Shadows"] = 5,
					["Deadly Poison"] = 3600.022,
					["Blade Twisting"] = 8,
					["Earthbind"] = 5,
					["Slice and Dice"] = 27,
					["Rupture"] = 12,
					["Combat Readiness"] = 20,
					["Dancing Steel"] = 12,
					["Vendetta"] = 20,
					["Drink"] = 20,
					["Food"] = 20,
					["Anticipation"] = 15,
					["Windswept Pages"] = 20,
					["Garrote"] = 18,
					["Blind"] = 60,
					["Tricks of the Trade"] = 6,
					["Recuperate"] = 24,
					["Weakened Soul"] = 15,
					["Jade Spirit"] = 12,
					["Moderate Insight"] = 15,
					["Arcane Missiles!"] = 20,
					["Sprint"] = 8,
					["Honorless Target"] = 30,
					["Hand of Protection"] = 10,
					["Resurrection Sickness"] = 600,
					["Deep Insight"] = 15,
					["Frostbolt"] = 9,
					["Revealing Strike"] = 15,
					["Paralytic Poison"] = 15,
					["Leeching Poison"] = 3600.022,
					["Shallow Insight"] = 15,
					["Grace"] = 15,
					["Recently Bandaged"] = 60,
					["Hurricane"] = 12,
					["Vanish"] = 3,
					["Eye of Vengeance"] = 10,
					["Arrow of Time"] = 20,
					["Harmony"] = 20,
					["River's Song"] = 7,
					["Blindside"] = 10,
					["Deserter"] = 900,
					["Kidney Shot"] = 2,
					["Enlightenment"] = 10,
					["First Aid"] = 8,
					["Plague of Ages"] = 9,
					["Adrenaline Rush"] = 20,
					["Killing Spree"] = 2,
					["Power Word: Shield"] = 15,
					["Forbearance"] = 60,
					["Paralysis"] = 4,
					["Rejuvenation"] = 12.597,
					["Cheap Shot"] = 4,
					["Evasion"] = 15,
				},
				["muteSFX"] = true,
			},
		},
	}
end
