-- 한글화 작업 : 달라란@삼이공
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Raven", "koKR")
if not L then return end

-- Main.lua
L["Raven"] = true
L["Raven left click"] = "|cffffff00좌클릭|r 옵션메뉴 열기/닫기"
L["Raven right click"] = "|cffffff00우클릭|r 바그룹 잠금"
L["Raven shift left click"] = "|cffffff00쉬프트 좌클릭|r Raven 활성화/비활성화"
L["Raven shift right click"] = "|cffffff00쉬프트 우클릭|r 블리자드 버프 전환"
L["Shared Potion Cooldown"] = "물약 쿨다운 공유"
L["Shared Elixir Cooldown"] = "영약 쿨다운 공유"
L["Global Cooldown"] = "글로벌 쿨다운"
L["GCD"] = "글쿨"-- abbreviation for Global Cooldown
L["Blood Rune"] = "혈기의 룬"
L["Unholy Rune"] = "부정의 룬"
L["Frost Rune"] = "냉기의 룬"
L["Death Rune"] = "죽음의 룬"
L["Failed to load "] = "불러오기 실패"
L["Not Tracking"] = "추적 안함"
L["Potions"] = "물약"
L["Elixirs"] = "비약"
L["Fire Totem"] = "불의 토템"
L["Water Totem"] = "물의 토템"
L["Earth Totem"] = "대지의 토템"
L["Air Totem"] = "바람의 토템"

-- Profile.lua
L["Frost School"] = "냉기 속성"
L["Fire School"] = "화염 속성"
L["Nature School"] = "자연 속성"
L["Shadow School"] = "암흑 속성"
L["Arcane School"] = "비전 속성"
L["Holy School"] = "신성 속성"
L["Physical School"] = "물리 속성"
L["Locked out of Frost school of magic."] = "냉기 속성의 마법을 밖에서 잠금"
L["Locked out of Fire school of magic."] = "화염 속성의 마법을 밖에서 잠금"
L["Locked out of Nature school of magic."] = "자연 속성의 마법을 밖에서 잠금"
L["Locked out of Shadow school of magic."] = "암흑 속성의 마법을 밖에서 잠금"
L["Locked out of Arcane school of magic."] = "비전 속성의 마법을 밖에서 잠금"
L["Locked out of Holy school of magic."] = "신성 속성의 마법을 밖에서 잠금"
L["Locked out of Physical school of magic."] = "물리 속성의 마법을 밖에서 잠금"

-- Bars.lua
L["Test Bar"] = "검사바"
L["Custom Bar Group"] = "사용자 정의 바 그룹"
L["Auto Bar Group"] = "자동 바 그룹"
L["Anchor attached"] = '|cffffff00부착|r 에 "'
L["Anchor left click 1"] = "|cffffff00좌클릭|r to unattach and then move the anchor"
L["Anchor left click 2"] = "|cffffff00좌클릭|r 앵커 이동"
L["Anchor right click"] = "|cffffff00우클릭|r 앵커 잠금 및 숨김"
L["Anchor shift left click"] = "|cffffff00쉬프트 좌클릭|r 바 검사"
L["Anchor shift right click"] = "|cffffff00쉬프트 우클릭|r 방향"
L["Anchor alt left click"] = "|cffffff00알트 좌클릭|r 옵션 메뉴 열기/닫기"
L["Anchor alt right click"] = "|cffffff00알트 우클릭|r to cycle through configurations"
L["Add filter"] = function(a, b, n) return string.format("Raven: \"%s\" added to %s filter list for bar group \"%s\"", a, b, n) end
L["Header click"] = "|cffffff00우클릭|r 숨김, 새로 대상으로 지정하거나 버프 또는 디버프 시전시 표시됨"
L["<Applied by "] = true

-- Conditions.lua
-- These strings are used in GetConditionText function to produce a detail condition description.
-- Many are also used in the options panel in the Conditions tab for defining tests.
L["Player Status"] = "플레이어 상태"
L["Target Status"] = "대상 상태"
L["Focus Status"] = "주시대상 상태"
L["All Buffs"] = "모든 버프"
L["Any Buffs"] = "특정 버프"
L["Buff Time Left"] = "버프 지속 시간"
L["Buff Count"] = "버프 갯수"
L["Buff Type"] = "버프 유형"
L["All Debuffs"] = "모든 디버프"
L["Any Debuffs"] = "특정 디버프"
L["Debuff Time Left"] = "디버프 지속 시간"
L["Debuff Count"] = "디버프 갯수"
L["Debuff Type"] = "디버프 유형"
L["All Cooldowns"] = "모든 쿨다운"
L["Spell Ready"] = "주문 준비"
L["Spell Casting"] = "주문 시전"
L["Item Ready"] = "아이템 준비"
L["Condition Name"] = function(name) return string.format("|cFF7adbf2조건 이름:|r %s", name) end
L["(not found)"] = "(찾을 수 없음)"
L["Disable String"] = " |cFFef2929[불가능]|r"
L["In Combat"] = "전투"
L["Out Of Combat"] = "전투 아님"
L["Is Resting"] = "휴식"
L["Not Resting"] = "휴식 아님"
L["Is Stealthed"] = "은신"
L["Not Stealthed"] = "은신 아님"
L["Is Fishing"] = "낚시"
L["Not Fishing"] = "낚시 아님"
L["Is Mounted"] = "탈것"
L["Not Mounted"] = "탈것 안탐"
L["Is PvP"] = "PvP"
L["Not PvP"] = "PvP 아님"
L["In Group"] = "그룹"
L["Not In Group"] = "그룹 아님"
L["In Party"] = "파티"
L["Not In Party"] = "파티 아님"
L["In Raid"] = "공격대"
L["Not In Raid"] = "공격대 아님"
L["In Instance"] = "인던"
L["Not In Instance"] = "인던 아님"
L["In Arena"] = "투기장"
L["Not In Arena"] = "투기장이 아님"
L["In Battleground"] = "전장"
L["Not In Battleground"] = "전장이 아님"
L["Primary Talents"] = "기본 특성"
L["If checked, bar group is shown when the player is in primary talents."] = "선택하면 플레이어가 기본 특성일 때, 바 그룹이 표시됩니다"
L["Secondary Talents"] = "보조 특성"
L["If checked, bar group is shown when the player is in secondary talents."] = "선택하면 플레이어가 보조 특성일 때, 바 그룹이 표시됩니다"
L["Has Pet"] = "소환수 있음"
L["No Pet"] = "소환수 없음"
L["Level String"] = function(x, level) return string.format("레벨 %s %d", x, level) end
L["Health String"] = function(x, minHealth) return string.format("생명력 %s %d%%", x, minHealth) end
L["Power String"] = function(x, minPower) return string.format("힘 %s %d", x, minPower) end
L["Holy Power String"] = function(x, minPower) return string.format("신성한 힘 %s %d", x, minPower) end
L["Shards String"] = function(x, minShards) return string.format("조각 %s %d", x, minShards) end
L["Eclipse String"] = function(x, power) return string.format("일/월식 힘 %s %d", x, power) end
L["Solar Eclipse"] = "일식"
L["Lunar Eclipse"] = "월식"
L["Combo Pts String"] = function(x, minComboPoints) return string.format("연계 점수 %s %d", x, minComboPoints) end
L["Stance String"] = function(stance) return string.format("태세 = \"%s\"", stance) end
L["Talent String"] = function(talent) return string.format("특성 = \"%s\"", talent) end
L["Blood"] = "혈기"
L["Frost"] = "냉기"
L["Unholy"] = "부정"
L["Rune"] = "룬"
L["Runes"] = "룬들"
L["Mainhand String"] = function(level) return string.format("주장비 >= %d", level) end
L["Offhand String"] = function(level) return string.format("보조장비 >= %d", level) end
L["Ranged String"] = function(level) return string.format("원거리 장비 >= %d", level) end
L["Exists"] = "존재함"
L["Not Exists"] = "존재하지 않음"
L["Is Player"] = "플레이어"
L["Not Player"] = "플레이어 아님"
L["Is Enemy"] = "적"
L["Not Enemy"] = "적 아님"
L["Is Friendly"] = "우호적"
L["Not Friendly"] = "우호적 아님"
L["Is Dead"] = "사망"
L["Not Dead"] = "사망 아님"
L["In Range"] = "사정거리 안"
L["Out Of Range"] = "사정거리 밖"
L["Is "] = true
L["Not "] = true
L["On"] = true
L["Not All Active"] = "모두 활성화 안함"
L["All Active"] = "모두 활성화"
L["None Active"] = "활성화 아닐 때 "
L["Any Active"] = "활성화일 때"
L["Cast By Player"] = "플레이어 시전"
L["Cast By Other"] = "플레이어외 시전"
L["Cast By Anyone"] = "모든사람이 시전한"
L["Missing"] = "없음"
L["Present"] = "현재의"
L["Less Than"] = "미만"
L["Or More"] = "이상"
L["Seconds"] = "초"
L["Seconds Or More"] = "초 이상"
L["Test Global Cooldown"] = "글로벌 쿨다운 검사"
L["Ignore Global Cooldown"] = "글로벌 쿨다운 무시"
L["Ignore Spell Usable"] = "사용가능 주문 무시"
L["Test Spell Usable"] = "사용가능 주문 검사"
L["Target In Range"] = "대상 사정거리 안"
L["Target Out Of Range"] = "대상 사정거리 밖"
L["Cast By"] = "시전자"							
L["Item Is Not Ready"] = "아이템 미준비"
L["Item Is Ready"] = "아이템 준비"
L["Dependencies String"] = "\n|cFF7adbf2Dependencies:|r"
L["True Color String"] = "|cFF8ae234참|r"
L["False Color String"] = "|cFFef2929거짓|r"
L["Logic AND String"] = "\n|cFF7adbf2논리로 테스트 평가 와, "
L["Logic OR String"] = "\n|cFF7adbf2논리로 테스트 평가 또는, "
L["Toggle String"] = "문자열 전환|r"
L["Toggle String"] = "\n|cFF7adbf2문자열 전환|r"
L["Set Result True"] = "\n|cFF7adbf2설정 결과 참|r"
L["Set Result False"] = "\n|cFF7adbf2설정 결과 거짓|r"
L["Normal"] = "일반"
L["Boss"] = "보스"
L["Elite"] = "정예"
L["Rare"] = "희귀"
L["Rare Elite"] = "희귀 정예"

-- Nest.lua
L["Right-to-left bars, label left, icon left"] = "바 우측에서 좌측, 라벨 좌측, 아이콘 좌측"
L["Left-to-right bars, label left, icon left"] = "바 좌측에서 우측, 라벨 좌측, 아이콘 좌측"
L["Right-to-left bars, label right, icon left"] = "바 우측에서 좌측, 라벨 우측, 아이콘 좌측"
L["Left-to-right bars, label right, icon left"] = "바 좌측에서 우측, 라벨 우측, 아이콘 좌측"
L["Right-to-left bars, label left, icon right"] = "바 우측에서 좌측, 라벨 좌측, 아이콘 우측"
L["Left-to-right bars, label left, icon right"] = "바 좌측에서 우측, 라벨 좌측, 아이콘 우측"
L["Right-to-left bars, label right, icon right"] = "바 우측에서 좌측, 라벨 우측, 아이콘 우측"
L["Left-to-right bars, label right, icon right"] = "바 좌측에서 우측, 라벨 우측, 아이콘 우측"
L["Icons in rows, with right-to-left mini-bars"] = "아이콘 행, 미니바 우측에서 좌측"
L["Icons in rows, with left-to-right mini-bars"] = "아이콘 행, 미니바 좌측에서 우측"
L["Icons in columns, right-to-left mini-bars"] = "아이콘 열, 미니바 우측에서 좌측"
L["Icons in columns, left-to-right mini-bars"] = "아이콘 열, 미니바 좌측에서 우측"
L["Icons on horizontal timeline, no mini-bars"] = "수평 시간대 아이콘, 미니바 아님"
L["Icons on vertical timeline, no mini-bars"] = "수직 시간대 아이콘, 미니바 아님"

-- L["Buff button right click"] = "|cffffff00우클릭|r 버프 취소"

-- Shared cooldowns
L["Portals"] = "포탈"
L["Summon Infernal/Doomguard"] = "지옥불정령/파멸의수호병 소환"
L["Shouts"] = "외침"
L["Pummel/Shield Bash"] = "자루치기/방패 밀어치기"
L["Crusader/Hammer"] = "성전사/망치"
L["Fire Traps"] = "화염 덫"
L["Frost Traps"] = "냉기 덫"
L["Earth/Fire Elementals"] = "대지/불의 정령"
L["Shocks"] = "충격"

-- All strings from here down are used for the options panel and are referenced in Options.lua.

L["Not valid string"] = function(n) return string.format("Raven: 위험 \"%s\" (은)는 올바른 주문 이름이 아닙니다", n) end
L["Circular string"] = function(a, b) return string.format("Raven: \"%s\" cannot be attached to \"%s\" because that creates a circular dependency", a, b) end
L["Dup bar group string"] = function(n) return string.format("중복된 이름\n사용중인 그룹 이름입니다 %s. 덮어쓰시겠습니까?", n) end
L["Dup condition string"] = function(n) return string.format("중복된 이름\n사용중인 조건 이름입니다 %s. 덮어쓰시겠습니까?", n) end
L["is a duplicate of an existing bar label"] = "이 라벨은 기본 바 라벨과 중복"
L["does not begin with a letter or contains restricted characters"] = "글자로 시작하지 않거나 제한된 문자를 포함"
L["Type and condition string"] = function(t, a) return string.format("|cFF7adbf2유형:|r %s\n|cFF7adbf2조건:|r %s", t, a) end
L["Associated spell string"] = function(s) return string.format("\n|cFF7adbf2관련 주문:|r %s", s) end
L["Action type source string"] = function(a, t, s) return string.format("|cFF7adbf2행동:|r %s\n|cFF7adbf2유형:|r %s\n|cFF7adbf2Source:|r %s", a, t, s) end
L["Type source string"] = function(t, s) return string.format("|cFF7adbf2유형:|r %s\n|cFF7adbf2소스:|r %s", t, s) end
L["Action on cast by string"] = function(m, c) return string.format("\n|cFF7adbf2Action On:|r %s\n|cFF7adbf2Cast By:|r %s", m, c) end

-- Blizzard Addons option table
L["Configure"] = "구성"
L["Open Raven's standalone options panel."] = "Raven의 독립형 옵션 패널 열기"

-- Setup tab
L["Setup"] = "설정"
L["Enable Raven"] = "Raven 활성화"
L["If checked, Raven is enabled, otherwise all features are disabled."] = "선택시, Raven 활성화, 그렇지 않으면 모든 기능을 사용할 수 없습니다."
L["Hide Blizzard Buffs"] = "블리자드 기본 버프바 숨김"
L["If checked, Raven will hide the default user interface for buffs."] = "선택시, 블리자드 기본 버프바 숨김"
L["Hide Blizzard Runes"] = "블리자드 기본 룬 숨김"
L["If checked, Raven will hide the default user interface for runes."] = true
L["Mute Raven Sound"] = "Raven 음향 음소거"
L["If checked, Raven will not play sound effects."] = true
L["Minimap Icon"] = "미니맵 아이콘"
L["If checked, Raven will add an icon to the minimap."] = "선택시, 미니맵에 아이콘 표시"
L["Standard Bar Groups"] = "표준 바 그룹"
L["Anchor description"] = "Raven은 버프, 디버프 및 쿨다운을 바와 아이콘으로 표시할 수 있습니다. " ..
	'당신은 "바 그룹" 탭 아래에 있는 여러 옵션을 사용하여 맞춤형 사용자 인터페이스를 설정할 수 있습니다. ' ..
	"처음 사용하면, 여기에 나열된 표준 바 그룹으로 시작하는 것이 더 쉽습니다. " ..
	'당신이 원하는 것들을 선택하고 다음 중 하나 "바 만들기" 또는 "아이콘 만들기"를 누릅니다". ' ..
	'당신은 바와 아이콘의 조합으로 구성된 여러 개의 타이머를 만들 수 있습니다.\n'
L["All buffs on you, sort by time left."] = "자신의 모든 버프, 시간을 기준으로 정렬"
L["Short Buffs"] = "짧은 버프"
L["Buffs on you lasting less than 2 minutes."] = "지속시간 2분미만 버프"
L["Long Buffs"] = "긴 버프"
L["Buffs on you lasting at least 2 minutes, sort and color by class."] = "최소 2분이상 버프, 정렬과 색상은 직업에따라."
L["Debuffs"] = "디버프"
L["Debuffs on you."] = "자신의 디버프"
L["Cooldowns"] = "쿨다운"
L["Cooldowns on your spells and trinkets lasting at least 2 seconds."] = "최소 2초이상 지속되는 자신의 주문과 장신구 쿨다운"
L["Target"] = "대상"
L["Buffs and debuffs you cast on the target."] = "자신이 시전한 대상의 버프와 디버프"
L["Focus"] = "주시대상"
L["Buffs and debuffs you cast on the focus."] = "자신이 시전한 주시대상의 버프와 디버프"
L["Totems"] = "토템"
L["Totem tracker bars for Shaman players."] = "주술사 유저를 위한 토템 추적 바"
L["Rune cooldown bars for Death Knights."] = "죽음의 기사의 룬 쿨다운바"
L["Notifications"] = "알림"
L["Common class-specific notifications."] = "일반적인 직업 고유 알림"
L["Buff Tracker"] = "버프 추적"
L["Buff tracker string"] = "당신이 시전한 버프가 있는 모든 대상 추적 (즉, HoT timers)"
L["Debuff Tracker"] = "디버프 추적"
L["Debuff tracker string"] = "당신이 시전한 디버프가 있는 모든 대상 추적 (즉, DoT timers)"
L["Timeline string"] = "주문과 장신구 쿨다운 아이콘 설정을 위한 타임라인"
L["Create As Bars"] = "바 만들기"
L["Create bars string"] = "바 중심의 형식을 사용하여 선택된 바 그룹을 만듭니다"
L["Create As Icons"] = "아이콘 만들기"
L["Create icons string"] = "아이콘 중심의 형식을 사용하여 선택된 아이콘 그룹을 만듭니다"
L["Configure string"] = "바그룹 만들기\n동일한 이름을 가진 기존의 바 그룹을 덮어써, 선택된 바 그룹을 만들시겠습니까?"
L["Reset selections."] = "선택 재설정"
L["Link"] = "연결"
L["Link settings string"] = "다른 프로필에 동일한 이름을 가진 바그룹을 선택된 바 그룹으로 연결 전환합니다. 연결된 바 그룹의 위치, 배치, 외형 및 타이머 옵션을 공유합니다.. 이 것은 여러 개의 캐릭터를 설정할 때 도움이 될 수 있습니다."
L["Delete the selected bar groups."] = "선택 바그룹 삭제"
L["Delete standard string"] = "바그룹 삭제\n선택된 바그룹을 삭제하시겠습니까?"
L["Bar Group Anchors"] = "바 그룹 앵커"
L["Bar group anchor string"] = "바 그룹은 바가 표시되는 앵커를 가지고 있습니다. " ..
	"Anchor tooltips list helpful shortcuts (e.g., change direction bars grow from the anchor, cycle through configuration choices, show test bars). " ..
	"You can left-click and drag anchors. " ..
	"위치가 마음에 들면 앵커를 우클릭하여 잠글 수 있습니다. " ..
	'잠겨져 숨겨있는 앵커는 "모든 앵커 잠금해제" 버튼으로 다시 표시할 수 있습니다.\n'
L["Lock All Anchors"] = "모든 앵커 잠금"
L["Lock and hide the anchors for all bar groups."] = "모든 바 그룹 잠금 및 앵커 숨김"
L["Unlock All Anchors"] = "모든 앵커 잠금해제"
L["Unlock and show the anchors for all bar groups."] = "모든 바 그룹 잠금해제 및 앵커 표시"

-- Defaults tab
L["Defaults"] = "기본값"
L["Defaults string"] = "바의 치수와 글꼴/질감 등 외형 옵션을 공유 합니다. " ..
	"You can adjust defaults for these options with settings in this section. " ..
	"These settings are shared across all profiles to simplify use with multiple characters.\n"
L["Bar Configurations"] = "바 구성"
L["Icon Configurations"] = "아이콘 구성"
L["Bar Width"] = "바 너비"
L["Set width of bars."] = "바 너비 설정"
L["Bar Height"] = "바 높이"
L["Set height of bars."] = "바 높이 설정"
L["Icon Size"] = "아이콘 크기"
L["Set width/height for icons."] = "아이콘 너비/높이 설정"
L["Scale"] = "스케일"
L["Set scale factor for bars and icons."] = "바 및 아이콘의 스케일 설정"
L["Horizontal Spacing"] = "수평 간격"
L["Adjust horizontal spacing between bars."] = "바 사이 수평 간격 설정"
L["Vertical Spacing"] = "수직 간격"
L["Adjust vertical spacing between bars."] = "바 사이 수직 간격 설정"
L["Icon Inset"] = "아이콘(좌우)"
L["Set icon's horizontal inset from bar."] = "바에서 아아콘의 수평 위치 설정"
L["Icon Offset"] = "아이콘(상하)"
L["Set vertical offset between icon and bar."] = "아이콘과 바 사이의 수직 위치 설정"
L["Reset Format"] = "형식 재설정"
L["Reset format to default settings."] = "기본 설정으로 형식 재설정"
L["RESET FORMAT\nAre you sure you want to reset the format options?"] = "형식 재설정\n형식 옵션을 재설정 하시겠습니까?"
L["Fonts and Textures"] = "글꼴 과 재질"
L["Label Text"] = "라벨 문자"
L["Font"] = "글꼴"
L["Select font."] = "글꼴 선택"
L["Font Size"] = "글꼴 크기"
L["Set font size."] = "글꼴 크기 설정"
L["Opacity"] = "투명도"
L["Set text opacity."] = "문자 투명도 설정"
L["Color"] = "색상"
L["Outline"] = "외각선"
L["Add black outline."] = "검은 테두리 추가"
L["Thick"] = "굵게"
L["Add thick black outline."] = "굵은 검은 테두리 추가"
L["Mono"] = "단일"
L["Render font without antialiasing."] = "글꼴 가장자리 밖으로 렌더"
L["Shadow"] = "그림자"
L["Show shadow with text."] = "문자에 그림자 보이기"
L["Time Text"] = "시간 문자"
L["Icon Text"] = "아이콘 문자"
L["Bars and Icons"] = "바와 아이콘"
L["Bar Foreground Texture"] = "바 전경질감"
L["Select foreground texture for bars."] = "전경 바의 질감 선택"
L["Foreground Opacity"] = "전경 투명도"
L["Set foreground opacity for bars."] = "전경 바의 투명도 설정"
L["Background Texture"] = "배경 질감"
L["Select background texture for bars."] = "배경 바의 질감 선택"
L["Background Opacity"] = "배경 투명도"
L["Set background opacity for bars."] = "배경 바의 투명도 설정"
L["Panels and Borders"] = "패널과 테두리"
L["Background Panel"] = "배경 패널"
L["Enable display of a background panel behind bar group."] = true
L["Panel Texture"] = "패널 질감"
L["Select texture to display in panel behind bar group."] = true
L["Adjust padding between bar group and the background panel and border."] = true
L["Set fill color for the panel."] = true
L["Background Border"] = "배경 테두리"
L["Select border to display behind bar group (select None to disable border)."] = true
L["Adjust inset from the border to background panel's fill color."] = true
L["Set color for the border."] = "설정 테두리 색상"
L["Bar Border"] = "바 테두리"
L["Select border for bars in the bar group (select None to disable border)."] = true
L["Adjust size of the border's edge."] = true
L["Adjust offset to the border from the bar."] = true
L["Set border's offset from the bar."] = true
L["Edge Size"] = true
L["Inset"] = true
L["Offset"] = true
L["Padding"] = true
L["Border Color"] = true
L["Panel Color"] = true
L["Foreground Saturation"] = "전경 채도"
L["Set saturation for foreground colors."] = "전경 색상의 채도 설정"
L["Foreground Brightness"] = "전경 밝기"
L["Set brightness for foreground colors."] = "전경 바의 밝기 설정"
L["Background Saturation"] = "배경 채도"
L["Set saturation for background colors."] = "배경 바의 투명도 설정"
L["Background Brightness"] = "배경 밝기"
L["Set brightness for background colors."] = "배경 바의 밝기 설정"
L["Opacity (Not Combat)"] = "투명도 (비전투시)"
L["Set opacity for bars when not in combat."] = "비전투시 바의 투명도 설정"
L["Opacity (In Combat)"] = "투명도 (전투시)"
L["Set opacity for bars when in combat."] = "전투시 바의 투명도 설정"
L["Icon Border Saturation"] = "아이콘 테두리 채도"
L["Set saturation for icon border colors."] = "아이콘 테두리 색상의 채도 설정"
L["Icon Border Brightness"] = "아이콘 테두리 밝기"
L["Set brightness for icon border colors."] = "아이콘 테두리 색상의 밝기 설정"
L["Reset Fonts/Textures"] = "글꼴/질감 재설정"
L["Reset fonts and textures to default settings."] = "글꼴과 질감을 기본값으로 재설정"
L["RESET FONTS/TEXTURES\nAre you sure you want to reset the font and texture options?"] = "글꼴/질감\n글꼴 및 질감 옵션을 재설정 하시겠습니까?"
L["Standard Colors"] = "기본 색상"
L["Bar Colors:"] = "바 색상:"
L["Notify"] = "알림"
L["Buff"] = "버프"
L["Debuff"] = "디버프"
L["Cooldown"] = "쿨다운"
L["Buffs"] = "버프"
L["Debuff Colors:"] = "디버프 색상:"
L["Curse"] = "저주"
L["Magic"] = "마법"
L["Disease"] = "질병"
L["Poison"] = "독"
L["Reset Bar Colors"] = "바 색상 재설정"
L["Reset bar colors back to default."] = "바 색상을 기본으로 재설정"
L["RESET BAR COLORS\nAre you sure you want to reset bar colors back to default?"] = "바 색상을 기본으로 재설정 하시겠습니까?"
L["Reset Debuff Colors"] = "디버프 색상 재설정"
L["Reset debuff colors back to default."] = "디버프 색상을 기본으로 재설정"
L["RESET DEBUFF COLORS\nAre you sure you want to reset debuff colors back to default?"] = "디버프 색상을 기본으로 재설정 하시겠습니까?"
L["OmniCC"] = "OmniCC"
L["Hide OmniCC"] = "OmniCC 표시 숨기기"
L["If checked, OmniCC counts are hidden on icons in all bar groups (requires /reloadui)."] = "체크시 모든 바 그룹의 아이콘에 OmniCC 카운트 표시를 숨김"
L["Masque/Button Facade"] = "Masque/Button Facade"
L["If checked, icons are skinned with Masque (formerly known as Button Facade)."] = "체크시 아이콘은 Masque/Button Facade 애드온 스킨으로 적용됌"
L["Color Normal Texture"] = "색상 일반 질감"
L["If checked, icon border color is applied to the normal texture."] = true
L["Color Border Texture"] = "색상 테두리 질감"
L["If checked, icon border color is applied to the border texture."] = "선택시, 아이콘 테두리 색상은 테두리 질감으로 적용됨"
L["Sound Channel"] = "사운드 채널"
L["Master"] = true
L["If checked, sound is played in Master channel."] = true
L["SFX"] = true
L["If checked, sound is played in SFX channel."] = true
L["Music"] = true
L["If checked, sound is played in Music channel."] = true
L["Ambience"] = true
L["If checked, sound is played in Ambience channel."] = true

-- Spells tab
L["Spells"] = "주문"
L["Spells string"] = "Spells have associated colors and labels which can be customized. " ..
	"Custom colors and labels are shared across all profiles to simplify use with multiple characters. " ..
	"You can also create spell lists and specify internal cooldowns and effect timers in this section.\n"
L["Colors and Labels"] = "색상과 라벨"
L["Spell Name"] = "주문 이름"
L["Enter spell name (or numeric identifier) whose color you want to change."] = "변경하고자하는 주문 이름(또는 주문ID)를 입력하십시오"
L["Select a standard color or click to set a custom color."] = "표준 색상을 선택하거나 사용자 정의 색상을 설정"
L["Spell Label"] = "주문 라벨"
L["Enter a label to be used by default with this spell."] = "이 주문에 기본으로 사용될 라벨을 입력하십시오"
L["Spell Sound"] = "주문 음향"
L["Select sound to associate with the spell."] = true
L["Reset"] = "재설정"
L["Reset color and label string"] = function(s) return string.format("%s의 색상과 라벨을 기본값으로 재설정", s) end
L["Reset color and label confirm"] = function(s) return string.format("주문 색상 재설정\n%s의 색상을 기본값으로 재설정 하시겠습니까?", s) end
L["Reset Spell Colors"] = "주문 색상 재설정"
L["Reset spell colors back to defaults."] = "주문 색상 기본값으로 재설정"
L["RESET SPELL COLORS\nAre you sure you want to reset all spell colors back to defaults?"] = "주문 색상 재설정\n모든 주문 색상을 기본값으로 재설정 하시겠습니까?"
L["Reset Spell Labels"] = "주문 라벨 재설정"
L["Reset spell labels back to defaults."] = "주문 라벨 기본값으로 재설정"
L["RESET SPELL LABELS\nAre you sure you want to reset all spell labels back to defaults?"] = "주문 라벨 재설정\n모든 주문 라벨을 기본값으로 재설정하시겠습니까?"
L["Reset Spell Sounds"] = "설정 주문 음향"
L["Reset spell sounds back to defaults."] = "설정 주문 음향을 기본으로 돌림"
L["RESET SPELL SOUNDS\nAre you sure you want to reset all spell sounds back to defaults?"] = true
L["Internal Cooldowns Triggered By Buffs/Debuffs"] = "내부 쿨다운을 버프/디버프로 발동"
L["Internal Cooldowns"] = "내부 쿨다운"
L["Enable detecting internal cooldowns."] = true
L["Cooldown List"] = "쿨다운 목록"
L["New Cooldown"] = "새 쿨다운"
L["Enter a new internal cooldown triggered by a buff or debuff."] = true
L["Enter Spell Name or ID"] = "주문 이름 또는 ID 입력"
L["Enter buff or debuff spell name or numeric identifier for new internal cooldown."] = true
L["Cancel creating a new internal cooldown."] = true
L["Delete Cooldown"] = "쿨다운 삭제"
L["Delete the selected internal cooldown."] = "선택된 내부 쿨다운 삭제"
L["Delete cooldown string"] = "DELETE COOLDOWN\nAre you sure you want to delete the selected internal cooldown?"
L["Enter duration in seconds."] = true
L["Enable detecting this internal cooldown."] = true
L["If checked, test if buffs/debuffs were cast by the player."] = true
L["Cast On Player"] = "플레이어에시전"
L["If checked, test if buffs/debuffs are on the player and cast by anyone other than the player."] = true
L["Reset List"] = "목록 재설정"
L["Enter comma-separated list of buffs or debuffs (either spell names or numeric identifiers) that reset the internal cooldown."] = true
L["Reset Cooldowns"] = "쿨다운 재설정"
L["Reset all internal cooldowns back to defaults."] = "모든 내부 쿨다운 기본값으로 재설정"
L["RESET COOLDOWNS\nAre you sure you want to reset all internal cooldowns back to defaults?"] = "쿨다운 재설정\n모든 내부 쿨다운을 기본값으로 재설정하시겠습니까?"
L["Effect Timers Triggered By Spell Casts"] = "주문 시전으로 발동하는 효과 타이머"
L["Enable detecting spell effects."] = true
L["Spell Effect List"] = true
L["New Spell Effect"] = "새로운 주문 효과"
L["Enter a new spell effect triggered by a successful spell cast."] = true
L["Enter spell name or numeric identifier that, when cast, will trigger a new spell effect."] = true
L["Cancel creating a new spell effect."] = true
L["If checked, spell effect is a buff."] = true
L["If checked, spell effect is a debuff."] = true
L["If checked, spell effect is a cooldown."] = true
L["Delete Spell Effect"] = "주문 효과 삭제"
L["Delete the selected spell effect."] = true
L["Delete effect string"] = "DELETE SPELL EFFECT\nAre you sure you want to delete the selected spell effect?"
L["Enable detecting this spell effect."] = true
L["Renew"] = true
L["If checked, spell effect is renewed if spell is cast again while effect is active."] = true
L["If checked, include name of caster in the label if spell effect is a buff or debuff."] = true
L["Enter spell name or numeric identifier for spell to be associated with this effect (default is to use spell that triggers the effect)."] = true
L["Required Talent"] = "필요한 능력"
L["Enter name or numeric identifier for talent required for effect to happen (leave blank if no talent required)."] = true
L["Required Buff"] = "필요한 버프"
L["Enter name or numeric identifier for buff required to be active on player for effect to happen (leave blank if no buff required)."] = true
L["Required Condition"] = "필요한 조건"
L["Enter name of condition required to be true for effect to happen (leave blank if no condition required)."] = true
L["If checked, spell must be cast by the player to trigger the spell effect."] = true
L["If checked, spell must be cast by the player's pet to trigger the spell effect."] = true
L["If checked, spell must be cast by the target to trigger the spell effect."] = true
L["If checked, spell must be cast by the focus to trigger the spell effect."] = true
L["If checked, spell must be cast by anyone other than the player or pet to trigger the spell effect."] = true
L["If checked, trigger the spell effect if the spell is cast by anyone, including player."] = true
L["Spell Lists"] = "주문 목록들"
L["Spell List"] = "주문 목록"
L["New Spell List"] = "새 주문 목록"
L["Create a new spell list."] = "새로운 주문 목록을생성."
L["Enter Spell List Name"] = "주문 목록 이름을 입력"
L["Enter name for a new spell list."] = "새로운 주문 목록에 대한 이름을 입력합니다."
L["Cancel creating a new spell list."] = "새 주문 목록을 생성 취소."
L["Delete Spell List"] = "주문 목록을 삭제합니다"
L["Delete the selected spell list."] = "선택한 주문 목록을 삭제합니다."
L["Delete spell list string"] = "주문 목록 문자열을 삭제,당신이 선택한 주문 목록을 삭제하시겠습니까?"
L["Enter Spell"] = "주문을 입력"
L["Enter a spell name (or numeric identifier, optionally preceded by # for a specific spell id) to be added to the list."] = "주문 이름을 입력(옵션 특정 주문 ID를 # 앞에 또는 숫자 식별자)목록에 추가."
L["Delete the selected spell from the list."] = "목록에서 선택한 주문을 삭제합니다."
L["Reset the spell list."] = "주문 목록을 재설정합니다."
L['RESET\nAre you sure you want to reset the spell list?'] = "재설정, 당신은 주문 목록을 재설정 하시겠습니까?"

-- Bar Groups tab
L["Bar Groups"] = "바 그룹들"
L["Bar Group"] = "바 그룹"
L["New Custom Group"] = "새 사용자 정의 그룹"
L["Create a new bar group with manually added bars."] = "수동으로 추가하는 바 그룹을 만듭니다"
L["New Auto Group"] = "새 자동 그룹"
L["Create a new bar group with automatically displayed bars."] = "자동으로 표시되는 바 그룹을 만듭니다"
L["Enter Custom Group Name"] = "사용자 정의 그룹 이름 입력"
L["Enter name of new custom bar group."] = "새 사용자 정의 바 그룹의 이름을 입력"
L["Invalid name."] = "잘못된 이름"
L["Enter Auto Group Name"] = "자동 그룹 이름 입력"
L["Enter name of new auto bar group."] = "새 자동 바 그룹의 이름을 입력"
L["Cancel"] = "취소"
L["Cancel creating a new bar group."] = "새로운 바 그룹 만들기 취소"
L["Delete Bar Group"] = "바 그룹 삭제"
L["Delete the selected bar group."] = "선택한 바 그룹 삭제"
L["Delete bar group string"] = function(s) return string.format( "바 그룹 삭제\n 당신은 % s의 바 그룹을 삭제하시겠습니까?", s) end

-- Bar Groups > General tab
L["General"] = "일반"
L["Settings"] = "설정"
L["Enable Bar Group"] = "바 그룹 활성화"
L["Enable bar group string"] = "선택시, 바 그룹이 활성화되고 앵커가 표시됩니다, " ..
	"그렇지 않으면 바 그룹이 비활성화되고 앵커가 표시되지 않습니다"
L["Merge Bar Group"] = "바 그룹 병합"
L["Merge bar group string"] = "선택시, 이 바 그룹을 다른 바그룹에 병합합니다 " ..
	"Bars are generated based on this bar group's custom or auto settings, including \"표시 조건\" and timer options, " ..
	"but are sorted and displayed using the other bar group's layout and appearance settings."
L["Link Settings"] = "설정 연결"
L["Link settings string"] = "선택시, 다른 프로필의 같은 이름의 바그룹의 " ..
	"위치, 배치, 외형, 그리고 타이머 옵션을 연결"
L["Save Settings"] = "설정 저장"
L["Click to save current settings to linked settings."] = "연결된 설정을 현재 설정으로 저장하려면 클릭하십시오"
L["Bar Group To Merge Into"] = "밑의 바 그룹으로 병합"
L["Select a bar group to merge into."] = "병합할 바 그룹 선택"
L["Rename Bar Group"] = "바 그룹 이름 바꾸기"
L["New Name"] = "새이름"
L["Enter new name for the bar group."] = "바 그룹의 새 이름을 입력"
L["Sort Order"] = "정렬 항목"
L["A to Z"] = "이름순"
L["If checked, sort in ascending alphabetical order starting at bar closest to the anchor."] = "선택시, 이름순로 정렬"
L["Time Left"] = "남은 시간"
L["If checked, sort by time left in ascending order starting at bar closest to the anchor."] = "선택시, 남은 시간순으로 정렬"
L["Duration"] = "전체 시간"
L["If checked, sort by overall duration in ascending order starting at bar closest to the anchor."] = "선택시, 전체 시간순으로 정렬"
L["Creation"] = "생성 시간"
L["If checked, show bars in order created with oldest bar closest to the anchor."] = "선택시, 생성 시간순으로 정렬"
L["Class"] = "직업"
L["If checked, sort by associated class name, if any, in ascending alphabetical order starting at bar closest to the anchor."] = "선택시, 직업 이름순으로 정렬"
L["Custom"] = "사용자 정의"
L["If checked, allow manually setting the order of bars."] = "선택시, 수동으로 바 순서를 설정"
L["Reverse Order"] = "역순"
L['If checked, reverse the sort order (e.g., "A to Z" becomes "Z to A").'] = "선택시, 정렬 목록을 역순으로 표시 (즉, \"A에서 Z\"를 \"Z에서 A\"로)"
L["Show When"] = "표시 조건"
L["If checked, bar group is shown when the player is in combat."] = "선택시, 플레이어가 전투시 바그룹 표시"
L["If checked, bar group is shown when the player is out of combat."] = "선택시, 플레이어가 비전투시 바그룹 표시"
L["Resting"] = "휴식"
L["If checked, bar group is shown when the player is resting."] = "선택시, 플레이어가 휴식중 바그룹 표시"
L["Mounted"] = "탈것"
L["If checked, bar group is shown when the player is mounted."] = "선택시, 플레이어가 탈것에 탄 상태 바그룹 표시"
L["Vehicle"] = "차량"
L["If checked, bar group is shown when the player is in a vehicle."] = "선택시, 플레이어가 차량에 탄 상태에 바그룹 표시"
L["Enemy"] = "적"
L["If checked, bar group is shown when the target is an enemy."] = "선택시, 대상이 적이면 바그룹 표시"
L["Friendly"] = "우호적"
L["If checked, bar group is shown when the target is friendly."] = "선택시, 대상이 우호적이면 바그룹 표시"
L["Focus=Target"] = "주시대상=대상"
L["If checked, bar group is shown when focus is same as target."] = "선택시, 주시대상이 대상과 같으면 바그룹 표시"
L["Solo"] = "솔로잉"
L["If checked, bar group is shown when the player is not in a party or raid."] = "선택시, 플레이어가 파티또는 공격대에 속해 있지 않을 때 바그룹 표시"
L["If checked, bar group is shown when the player is in a party."] = "선택시, 플레이어가 파티에 속해 있을 때 바그룹 표시"
L["If checked, bar group is shown when the player is in a raid."] = "선택시, 플레이어가 공격대에 속해 있을 때 바그룹 표시"
L["If checked, bar group is shown when the player is in a 5-man or raid instance."] = "선택하면 플레이어가 5 사람 또는 RAID 인스턴스에있을 때, 바 그룹이 표시됩니다."
L["If checked, bar group is shown when the player is not in a 5-man or raid instance."] = "선택하면 플레이어가 5 사람 또는 RAID 인스턴스에없는 경우 바 그룹이 표시됩니다."
L["If checked, bar group is shown when the player is in an arena."] = "선택시, 플레이어가 투기장에 속해 있을 때 바그룹 표시"
L["If checked, bar group is shown when the player is in a battleground."] = "선택시, 플레이어가 전장에 속해 있을 때 바그룹 표시"
L["Fishing"] = " 낚시중 "
L["If checked, bar group is shown when the player is ready to fish (i.e., trained with fishing pole equipped)."] = "선택시, 플레이어가 낚시 준비를 했을 때 바그룹 표시 (즉, 낚시대 장착 상태)"
L["Blizzard Buffs Enabled"] = "블리자드 버프 활성화"
L["If checked, the bar group is shown if the default user interface for buffs is enabled."] = "선택시, 버프의 기본 사용자 인터페이스가 활성화된 경우 바 그룹 표시"
L["Blizzard Buffs Disabled"] = "블리자드 버프 비활성화"
L["If checked, the bar group is shown if the default user interface for buffs is disabled."] = "선택시, 버프의 기본 사용자 인터페이스가 비활성화된 경우 바 그룹 표시"
L["Condition Is True"] = " 조건이 참일 경우"
L["If checked, bar group is shown only when the selected condition is true."] = "선택시, 조건이 참일 경우 바그룹 표시"
L["Condition"] = "조건"
L["Player Class"] = "플레이어 직업"
L["Start Spell Sound"] = "시작하는 주문 음향"
L["Play associated spell sound, if any, when bar starts (spell sounds are set up on Spells tab)."] = true
L["Alternative Start Sound"] = true
L["Select sound to play when bar starts and there is no associated spell sound (or start spell sounds are not enabled)."] = true
L["Replay"] = true
L["Enable replay of start sound (after a specified amount of time) while bar is active."] = true
L["Replay Time"] = true
L["Replay Start Sound"] = true
L["Set number of seconds between replays of start sound."] = true
L["Finish Spell Sound"] = "끝나는 주문 음향"
L["Play associated spell sound, if any, when bar finishes (spell sounds are set up on Spells tab)."] = true
L["Alternative Finish Sound"] = true
L["Select sound to play when bar finishes and there is no associated spell sound (or finish spell sounds are not enabled)."] = true
L["Expire Spell Sound"] = "만료돼는 주문 음향"
L["Play associated spell sound, if any, when bar is about to expire (spell sounds are set up on Spells tab)."] = true
L["Alternative Expire Sound"] = true
L["Select sound to play when bar is about to expire and there is no associated spell sound (or expire spell sounds are not enabled)."] = true
L["Expire Time"] = true
L["Set number of seconds before expiration that bar should change color and/or play expire sound."] = true
L["Minimum Duration"] = "최소 소요 시간"
L["Set minimum duration in minutes required to trigger expiration options."] = "만료 옵션을 실행하는 데 필요한 분 최소 기간을 설정합니다."
L["Color When Expiring"] = "색상 만료"
L["Enable color changes for expiring bars (and, for icon configurations, make background visible if opacity is set to invisible to enable bar as highlight)."] = "바 만료에 대한 색상 변경 사용(그리고, 아이콘 구성, 투명도가 강조로 바 있도록 보이지으로 설정된 경우 배경을 볼 수도 있습니다)."
L["Set bar color for when about to expire (set invisible opacity to disable color change)."] = "만료 때 표시줄 색상을 설정(컬러 변경을 해제하는 보이지 않는 불투명도를 설정)."
L["Set label color for when bar is about to expire (set invisible opacity to disable color change)."] = "막대가 만료하는 때 설정 라벨 색상(컬러 변경을 해제하는 보이지 않는 불투명도를 설정)."
L["Set time color for when bar is about to expire (set invisible opacity to disable color change)."] = "막대가 만료하는 때 설정 시간 색상(컬러 변경을 해제하는 보이지 않는 불투명도를 설정)."
L["Combat Text"] = "전투 텍스트"
L["Enable warning in combat text for expiring bars."] = "만료중인 바의 전투 텍스트 경고를 사용합니다"
L["Critical"] = "중요"
L["Enable combat text warning as critical."] = "전투 텍스트 경고와 같은 중요 설정합니다."
L["Set color for combat text warning."] = "전투 텍스트 경고 색상을 설정합니다."
L["expiring"] = "만료"
L["Miscellaneous Options"] = "기타 옵션"
L["Frame Strata"] = "프레임 우선순위"
L["Frame strata string"] = "다른 UI 요소 앞이나 뒤에 나타나는 바 그룹을 만들 때, 프레임에 대한 일반적인 우선순위를 선택합니다"
L["Lock"] = "잠금"
L["Lock and hide the anchor for the bar group."] = "바 그룹 앵커 잠금 및 숨김"
L["Unlock"] = "잠금해제"
L["Unlock and show the anchor for the bar group."] = "바 그룹의 앵커 잠금해제 및 보기"
L["Non-Interactive"] = "비 상호작용"
L["If checked, the bar group is non-interactive and doesn't show tooltips or respond to clicks."] = "선택시, 바그룹은 비 상호작용되고 툴팁 보기 또는 클릭에 반응하지 않음"
L["Only Icons Interact"] = "아이콘만 상호작용"
L["If checked, only icons show tooltips and respond to clicks, otherwise entire bar does."] = "선택시, 아이콘만 툴팁 보기 및 클릭에 반응하고, 그렇지 않으면 모든 바가 됨"
L["Tooltip Anchor"] = "툴팁 앵커"
L["Tooltip anchor string"] = "툴팁의 앵커 위치 선택 (\"DEFAULT\"는 툴팁 앵커를 자동으로 조정)"
L["Combat Tooltips"] = "전투 툴팁"
L["If checked, tooltips are shown during combat."] = "선택시, 툴팁을 전투중 표시"
L["Caster"] = true
L["If checked, tooltips include caster for buffs and debuffs when known."] = true
L["Show Headers"] = "헤더 보기"
L["When showing all buffs or debuffs cast by player, add headers for each affected target."] = true
L["Sort Target First"] = "대상을 첫번째로 정렬"
L["When showing all buffs or debuffs cast by player, sort ones for target first."] = true
L["Non-Target Opacity"] = "대상이 아닐 시 투명도"
L["When showing all buffs or debuffs cast by player, set opacity for ones not on target."] = true
L["Targets"] = true
L["When showing all buffs or debuffs cast by player without headers, show target names in labels."] = true
L["When showing all buffs or debuffs cast by player without headers, show spell names in labels."] = true

-- Bar Groups > Custom Bars tab
L["Custom Bars"] = "사용자 정의 바"
L["New"] = "새로운"
L["Create a new bar."] = "새 바 만들기"
L["Delete the selected bar."] = "선택 바 삭제"
L['DELETE BAR\nAre you sure you want to delete the selected bar?'] = "바 삭제\n선택된 바를 삭제하시겠습니까?"

-- Bar Groups > Buffs tab
L["Auto Buffs"] = "자동 버프"
L['Enable automatically displaying bars for buffs that match these settings.'] = "자동으로 해당 설정에 일치하는 버프에 대한 바 표시 활성화"
L["All Cast By Player"] = "플레이어의 모든 주문"
L['Include all buffs cast by player on others.'] = "플레이어가 시전한 모든 버프 포함"
L["Action On"] = "행동 대상"
L["If checked, only add bars for buffs if they are on the player."] = "선택시, 플레이어의 버프만 표시" 
L["If checked, only add bars for buffs if they are on the player's pet."] = "선택시, 플레이어의 소환수의 버프만 표시"
L["If checked, only add bars for buffs if they are on the target."] = "선택시, 대상의 버프만 표시"
L["If checked, only add bars for buffs if they are on the focus."] = "선택시, 주시대상의 버프만 표시"
L["Exclude On"] = "제외 목록"
L["If checked, exclude buffs if they are on the player."] = "선택시, 플레이어의 버프 제외"
L["If checked, exclude buffs if they are on the player's pet."] = "선택시, 플레이어의 소환수의 버프 제외"
L["If checked, exclude buffs if they are on the target."] = "선택시, 대상의 버프 제외"
L["If checked, exclude buffs if they are on the focus."] = "선택시, 주시대상의 버프 제외"
L["Mouseover"] = "마우스오버"
L["Pet's Target"] = "소환수의 대상"
L["Target's Target"] = "대상의 대상"
L["Focus's Target"] = "주시대상의 대상"
L["If checked, only add bars for buffs if they are on the mouseover unit."] = "선택시, 마우스오버한 유닛의 버프만 표시"
L["If checked, only add bars for buffs if they are on the pet's target."] = "선택시, 소환수의 대상의 버프만 표시"
L["If checked, only add bars for buffs if they are on the target's target."] = "선택시, 대상의 대상의 버프만 표시"
L["If checked, only add bars for buffs if they are on the focus's target."] = "선택시, 주시대상의 대상의 버프만 표시"
L["If checked, only add bars for buffs if cast by the player."] = "선택시, 플레이어가 시전한 버프만 표시"
L["If checked, only add bars for buffs if cast by the player's pet."] = "선택시, 플레이어의 소환수가 시전한 버프만 표시"
L["If checked, only add bars for buffs if cast by the target."] = "선택시, 대상이 시전한 버프만 표시"
L["If checked, only add bars for buffs if cast by the focus."] = "선택시, 주시대상이 시전한 버프만 표시"
L["If checked, only add bars for buffs if cast by anyone other than the player or pet."] = "선택시, 플레어어 또는 소환수를 제외한 모든 사람이 시전한 버프만 표시"
L["If checked, add bars for buffs if cast by anyone, including player."] = "선택시, 모든사람이 시전한 버프 표시, 플레이어 포함"
L["Other"] = '기타'
L["Anyone"] = "모든 사람"
L["Filter By Type"] = "필터 타입"
L["Filter buff types string"] = "선택시, 선택된 유형의 버프만 표시"
L["Tracking"] = "추적"
L["Include Tracking"] = "추적 포함"
L["Show Only Tracking"] = "추적한 것만 보기"
L['Include the active tracking types as buffs.'] = "활성화된 추적 유형 포함"
L['Include only the active tracking types.'] = "활성화된 추적 유형만 포함"
L["Stealable"] = "마법훔치기 할 수있는 것"
L['Include buffs that mages can spellsteal.'] = "마법사가 마법훔치기 할 수 있는 버프 포함"
L['Include magic buffs (these can usually be removed with abilities like Purge).'] = "마법 버프 포함 (일반적으로 정화와 같은 능력으로 제거할 수 있는 것)"
L['Include other buffs not selected with filter types.'] = "필터 유형으로 선택되지 않은 다른 버프 포함"
L["Filter List"] = "필터 목록"
L["Black List"] = "블랙 리스트"
L["White List"] = "화이트 리스트"
L["Use Spell List"] = "맞춤법 목록을 사용"
L["If checked, filter list includes spells in specified spell list (these are set up on the Spells tab)."] = "선택하는 경우 필터 목록은 지정된 철자 목록에서 주문을 포함"
L["If checked, don't display any buffs that are in the filter list."] = "선택시, 필터 목록에 있는 버프를 표시하지 않음"
L["If checked, only display buffs that are in the filter list."] = "선택시, 필터 목록에 있는 버프만 표시"
L["If checked, the filter list is shared with bar groups in other profiles with the same name."] = "선택시, 다른 프로필에 같은 이름으로 된 바그룹과 버프 목록 공유"
L["Enter Buff"] = "버프 입력"
L["Enter a buff to be added to the filter list."] = "필터 목록에 추가할 버프 입력"
L["Delete the selected buff from the filter list."] = "선택된 버프를 필터 목록에서 삭제"
L["Reset the buff filter list."] = "버프 필터 목록 초기화"
L['RESET\nAre you sure you want to reset the buff filter list?'] = "초기화\n버프 필터 목록을 초기화 하시겠습니까?"
L["Filter Bar Group"] = "바 그룹 필터"
L["Select filter bar group."] = "바 그룹 필터 선택"
L["Filter buff bar group string"] = "선택시, 선택된 바그룹도 버프를 표시하지 않음. 사용자 정의 바 그룹을 선택한 경우, 그 사용자 정의 바 목록에 버프를 표시하지 않음. 자동 바 그룹을 선택한 경우, 그 필터 목록에 버프를 표시하지 않음."

-- Bar Groups > Debuffs tab
L["Auto Debuffs"] = "자동 디버프"
L['Enable automatically displaying bars for debuffs that match these settings.'] = "자동으로 해당 설정에 일치하는 디버프에 대한 바 표시 활성화"
L['Include all debuffs cast by player on others.'] = "플레이어가 시전한 모든 디버프 포함"
L["Only Show Dispellable"] = "해제할 수 있는 것만 보기"
L['If check, only show debuffs that can be dispelled by the player.'] = "선택시, 플레이어가 해제할 수 있는 디버프만 보기"
L["If checked, exclude debuffs if they are on the player."] = "선택시, 플레이어의 디버프 제외"
L["If checked, exclude debuffs if they are on the player's pet."] = "선택시, 플레이어의 소환수의 디버프 제외"
L["If checked, exclude debuffs if they are on the target."] = "선택시, 대상의 디버프 제외"
L["If checked, exclude debuffs if they are on the focus."] = "선택시, 주시대상의 디버프 제외"
L["If checked, only add bars for debuffs if they are on the player."] = "선택시 플레이어의 디버프만 표시"
L["If checked, only add bars for debuffs if they are on the player's pet."] = "선택시, 플레이어의 소환수의 디버프만 표시"
L["If checked, only add bars for debuffs if they are on the target."] = "선택시, 대상의 디버프만 표시"
L["If checked, only add bars for debuffs if they are on the focus."] = "선택시, 주시대상의 디버프만 표시"
L["If checked, only add bars for debuffs if they are on the mouseover unit."] = "선택시, 마우스오버한 유닛의 디버프만 표시"
L["If checked, only add bars for debuffs if they are on the pet's target."] = "선택시, 소환수의 대상의 디버프만 표시"
L["If checked, only add bars for debuffs if they are on the target's target."] = "선택시, 대상의 대상의 디버프만 표시"
L["If checked, only add bars for debuffs if they are on the focus's target."] = "선택시, 주시대상의 대상의 디버프만 표시"
L["If checked, only add bars for debuffs if cast by the player."] = "선택시, 플레이어가 시전한 디버프만 표시"
L["If checked, only add bars for debuffs if cast by the player's pet."] = "선택시, 플레이어의 소환수가 시전한 디버프만 표시"
L["If checked, only add bars for debuffs if cast by the target."] = "선택시, 대상이 시전한 디버프만 표시"
L["If checked, only add bars for debuffs if cast by the focus."] = "선택시, 주시대상이 시전한 디버프만 표시"
L["If checked, only add bars for debuffs if cast by anyone other than the player or pet."] = "선택시, 플레이어 또는 소환수를 제외한 모든 사람이 시전한 디버프만 표시"
L["If checked, add bars for debuffs if cast by anyone, including player."] = "선택시, 모든사람이 시전한 디버프 표시, 플레이어 포함"
L["If checked, don't display any debuffs that are in the filter list."] = "선택시, 필터 목록에 있는 디버프를 표시하지 않음"
L["If checked, only display debuffs that are in the filter list."] = "선택시, 필터 목록에 있는 디버프만 표시"
L["Dispellable"] = "해제할 수있는 것"
L["Filter debuff types string"] = "선택시, 선택된 유형의 디버프만 표시"
L['Include other debuffs not selected with filter types.'] = "필터 유형으로 선택되지 않은 다른 디버프 포함"
L['Include debuffs that the player can dispel.'] = "플레이어가 해제할 수 있는 디버프 포함"
L['Include debuffs cast by boss.'] = "보스가 시전한 디버프 포함"
L['Include poison debuffs.'] = "독 디버프 포함"
L['Include curse debuffs.'] = "저주 디버프 포함"
L['Include magic debuffs.'] = "마법 디버프 포함"
L['Include disease debuffs.'] = "질병 디버프 포함"
L["If checked, the debuff filter list is shared with bar groups in other profiles with the same name."] = "선택시, 다른 프로필에 같은 이름으로 된 바그룹과 디버프 목록 공유"
L["Enter Debuff"] = "디버프 입력"
L["Enter a debuff to be added to the filter list."] = "필터 목록에 추가할 디버프 입력"
L["Delete the selected debuff from the filter list."] = "선택된 디버프를 필터 목록에서 삭제"
L["Reset the debuff filter list."] = "디버프 필터 목록 초기화"
L['RESET\nAre you sure you want to reset the debuff filter list?'] = "초기화\n디버프 필터 목록을 초기화하시겠습니까?"
L["Filter debuff bar group string"] = "선택시, 선택된 바그룹도 디버프를 표시하지 않음. 사용자 정의 바 그룹을 선택한 경우, 그 사용자 정의 바 목록에 디버프를 표시하지 않음. 자동 바 그룹을 선택한 경우, 그 필터 목록에 디버프를 표시하지 않음."

-- Bar Groups > Cooldowns tab
L["Auto Cooldowns"] = "자동 쿨다운"
L['Enable automatically displaying bars for cooldowns that match these settings.'] = "자동으로 해당 설정에 일치하는 쿨다운에 대한 바 표시 활성화"
L["Action By"] = "시전자"
L["If checked, only add bars for cooldowns associated with the player."] = "선택시, 플레이어와 관련된 쿨다운만 표시"
L["If checked, only add bars for cooldowns associated with the player's pet."] = "선택시, 플레이어의 소환수와 관련된 쿨다운만 표시"
L["If checked, add bars for cooldowns cast by either player or player's pet."] = "선택시, 플레이어 또는 플레이어의 소환수의 쿨다운 표시"
L["Include"] = "포함"
L["If checked, include bars for spell cooldowns."] = "선택시, 주문 쿨다운 포함"
L["Trinkets"] = "장신구"
L["If checked, include bars for cooldowns on equipped trinkets."] = "선택시, 장신구의 쿨다운 포함"
L["If checked, include bars for internal cooldowns triggered by a buff or debuff."] = true
L["Effect Timers"] = true
L["If checked, include bars for effect timers triggered by a spell cast."] = true
L["Weapon Buffs"] = "무기 버프"
L["If checked, include bars for weapon buffs."] = "체크시 무기 버프바를 포함"
L["Potions/Elixirs"] = "물약/비약"
L["If checked, include bars for shared potion/elixir cooldowns (an item subject to the shared cooldown must be in your bags in order for the cooldown to be detected)."] = "선택시, 물약/비약의 공유 쿨다운 포함(an item subject to the shared cooldown must be in your bags in order for the cooldown to be detected)"
L["If checked, include bars for other cooldowns (for item cooldowns, an item subject to the cooldown must be in your bags in order for the cooldown to be detected)."] = "선택시, 다른 쿨다운 포함(for item cooldowns, an item subject to the cooldown must be in your bags in order for the cooldown to be detected)"
L["Shared Cooldowns"] = "쿨다운 공유"
L["If checked, only show one cooldown for hunter Frost Traps."] = "선택시, 사냥꾼의 냉기 덫중 하나의 쿨다운만 보기"
L["If checked, only show one cooldown for hunter Fire Traps."] = "선택시, 사냥꾼의 화염 덫중 하나의 쿨다운만 보기"
L["If checked, only show one cooldown for shaman Shocks."] = "선택시, 주술사의 충격중 하나의 쿨다운만 보기"
L["If checked, only show one cooldown for paladin Crusader Strike and Hammer of the Righteous."] = "선택시, 성기사의 성전사의 일격과 정의의 망치중 하나의 쿨다운만 보기"
L["Filter Cooldowns"] = "쿨다운 필터"
L["If checked, don't display any cooldowns that are in the filter list."] = "선택시, 필터 목록에 있는 쿨다운을 표시하지 않음"
L["If checked, only display cooldowns that are in the filter list."] = "선택시, 필터 목록에 있는 쿨다운만 표시"
L["If checked, the cooldown filter list is shared with bar groups in other profiles with the same name."] = "선택시, 다른 프로필에 같은 이름으로 된 바그룹과 쿨다운 목록 공유"
L["Enter Cooldown"] = "쿨다운 입력"
L["Enter a cooldown to be added to the filter list."] = "필터 목록에 추가할 쿨다운 입력"
L["Delete the selected cooldown from the filter list."] = "선택된 쿨다운을 필터 목록에서 삭제"
L["Reset the cooldown filter list."] = "쿨다운 필터 목록 초기화"
L['RESET\nAre you sure you want to reset the cooldown filter list?'] = "선택된 쿨다운을 필터 목록에서 삭제"
L["Filter cooldown bar group string"] = "선택시, 선택된 바그룹도 쿨다운을 표시하지 않음. 사용자 정의 바 그룹을 선택한 경우, 그 사용자 정의 바 목록에 쿨다운을 표시하지 않음. 자동 바 그룹을 선택한 경우, 그 필터 목록에 쿨다운을 표시하지 않음."

-- Bar Groups > Layout tab
L["Layout"] = "배치"
L["Configuration"] = "구성"
L["Bars"] = "바"
L["If checked, use a bar-oriented configuration."] = "선택시, 바 위주의 구성 사용"
L["Icons"] = "아이콘"
L["If checked, use an icon-oriented configuration."] = "선택시, 아이콘 위주의 구성 사용"
L["Options"] = "옵션"
L["Select a configuration option for bars or icons."] = "바 또는 아이콘의 구성 옵션 선택"
L["Direction"] = "방향"
L["If checked, grow up or to the right, otherwise grow down or to the left."] = "선택시, 위 또는 우측, 그렇지않으면 아래  또는 좌측"
L["Copy Layout From"] = "(으)로부터 배치 복사"
L["Select bar group to copy all layout settings from."] = "을 선택 바 그룹에서 모두 레이아웃 설정을 복사합니다."
L["Timeline"] = "타임라인"
L["Width"] = "폭"
L["Set width of timeline."] = "타임라인 폭 설정"
L["Height"] = "높이"
L["Set height of timeline."] = "타임라인 높이 설정"
L["Set maximum duration represented on the timeline in seconds."] = "초 단위로 타임 라인에 표시 최대 기간을 설정합니다."
L["Exponent"] = "대표자"
L["Set exponent factor for timeline to adjust time scale."] = "타임라인을 위한 시간 규모 조정 지수 계수를 설정합니다"
L["Label List"] = "레이블 목록"
L['Enter comma-separated list of times to show as labels on the timeline (times are in seconds unless you include "m", which is included in the label, or "M", which is hidden, for minutes).'] = '타임 라인에있는 라벨에 표시할 시간을 쉼표로 구분된 목록을 입력(times are in seconds unless you include "m", which is included in the label, or "M", which is hidden, for minutes).'
L["Texture"] = "질감"
L["Select texture for timeline."] = "타임 라인에 대한 질감을 선택합니다."
L["Opacity"] = "투명도"
L["Set opacity for timeline."] = "타임 라인에 대한 투명도를 설정합니다."
L["Timeline Color"] = "타임 라인 색상"
L["Set color for timeline background."] = "타임 라인 배경 색상을 설정합니다."
L["Splash Effect"] = "스플래쉬 효과"
L["If checked, show a splash effect when icons expire."] = "선택하면 아이콘이 만료되면, 스플래시 효과를 보여줍니다."
L["Overlap Switch"] = "스위치 오버랩"
L["If checked, when icons overlap, switch every two seconds which is shown on top (otherwise always show icon with shortest time remaining on top)."] = "선택하면, 아이콘이 중복될 경우 상위에 2초 동안 표시됩니다.(그렇지 않으면 항상 상단에 남은 짧은 시간에 아이콘 표시)"
L["Hide Empty"] = "빈공간 숨기기"
L["If checked, hide the timeline background when there are no active icons."] = "선택하면 활성 아이콘이없는 경우, 타임 라인 배경을 숨깁니다."
L["If checked, format options are set to default values."] = "선택시, 형식 옵션을 기본값으로 설정"
L["Reset format for this bar group back to the current defaults."] = "이 바 그룹의 형식을 기본값으로 복원"
L["Format"] = "형식"
L["Icon"] = "아이콘"
L["Show icon string"] = "아이콘 보기 (참고 : 중첩개수 오버레이는 아이콘이 표시되지 않은 경우 숨겨져 바 라벨에 중첩 개수를 추가해서 표시함)"
L["Clock"] = "시계"
L["Show clock animation on icons for timer bars."] = "아이콘에 시계 애니메이션 보기"
L["Bar"] = "바"
L["Show colored bar and background."] = "색상 바와 배경 보기"
L["Spark"] = "불꽃"
L["Show spark that moves across bars to indicate remaining time."] = "남은 시간을 나타내는 바의 불꽃 보기"
L["Label"] = "라벨"
L["Show label text on bars."] = "바의 라벨 문자 보기"
L["Count"] = "중첩"
L["Show stack count in parentheses after label (it is also displayed as overlay on icon)."] = "라벨 뒤에 괄호에 중첩 개수를 표시합니다.(그것도 아이콘 오버레이로 표시됩니다)"
L["Time"] = "시간"
L["Show time left on bars that have a duration."] = "지속시간을 가지는 바의 남은 시간 보기"
L["Tooltips"] = "툴팁"
L["Show tooltips when the cursor is over a bar's icon."] = "바의 아이콘에 툴팁 보기"
L["Text Settings"] = "문자 설정"
L["Label Text Inset"] = "라벨 문자(좌우)"
L["Set horizontal inset for label from edge of bar."] = "바의 모서리부터 라벨에 대한 수평 inset 설정"
L["Label Text Offset"] = "라벨 문자(상하)"
L["Set vertical offset for label text from center of bar."] = "바의 중심부터 라벨 문자에 대한 수직 offset 설정"
L["Wrap"] = "줄바꿈"
L["If checked, wrap label text when it doesn't fit in the bar's width."] = "선택시, 바의 너비에 맞지 않을 경우 라벨 문자 줄바꿈"
L["Top"] = "상단"
L["If checked, set \"Top\" alignment for label text."] = "선택시, \"상단\"으로 라벨 문자 설정"
L["Middle"] = "중간"
L["If checked, set \"Middle\" alignment for label text."] = "선택시, \"중간\"으로 라벨 문자 설정"
L["Bottom"] = "하단"
L["If checked, set \"Bottom\" alignment for label text."] = "선택시, \"하단\"으로 라벨 문자 설정"
L["Time Text Inset"] = "시간 문자(좌우)"
L["Set horizontal inset for time text from edge of bar."] = "바의 모서리부터 시간 문자에 대한 수평 inset 설정"
L["Time Text Offset"] = "시간 문자(상하)"
L["Set vertical offset for time text from center of bar."] = "바의 중심부터 시간 문자에 대한 수직 offset 설정"
L["If checked, use normal alignment with small inset for time and label texts."] = "시간 및 라벨 문자의 작은 inset의 일반 정렬 사용"
L["Left"] = "좌측"
L["If checked, set \"Left\" alignment for time text and normal alignment for label."] = "선택시, \"좌측\"으로 시간 문자와 라벨의 일반 정렬 설정"
L["Center"] = "중심"
L["If checked, set \"Center\" alignment for time text and normal alignment for label."] = "선택시, \"중심\"으로 시간 문자와 라벨의 일반 정렬 설정"
L["Right"] = "우측"
L["If checked, set \"Right\" alignment for time text and normal alignment for label."] = "선택시, \"우측\"으로 시간 문자와 라벨의 일반 정렬 설정"
L["Icon Text Inset"] = "아이콘 문자(좌우)"
L["Set horizontal inset for icon text from middle of icon."] = "아이콘의 중간부터 아이콘 문자에 대한 수평 inset 설정"
L["Icon Text Offset"] = "아이콘 문자(상하)"
L["Set vertical offset for icon text from center of icon."] = "아이콘의 중심부터 아이콘 문자에 대한 수직 offset 설정"
L["If checked, time text is shown on the icon instead of the bar."] = true
L["Icon Configuration Options"] = "아이콘 배치 옵션"
L["Set how many bars/icons to display before wrapping to next row or column. If this is set to 0 then wrapping is disabled."] = "줄바꿈 하기 전, 열 또는 행의 한 줄의 아이콘 수 설정"
L["Wrap Direction"] = "줄바꿈 방향"
L["If checked, wrap icons up when arranged in rows or to the right when arranged in columns, otherwise wrap down or to the left."] = "선택시, 줄바꿈 방향은 위 또는 우측, 그렇지 않으면 아래 또는 좌측"
L["Snap To Center"] ="중심에 맞춤"
L["If checked and the bar group is locked, icons snap to center at the anchor position."] = true
L["Display Position"] = "표시 위치"
L["Horizontal"] = "가로"
L["Set horizontal position as percentage of overall width (cannot move beyond edge of display)."] = "전체 너비에 대한 비율로 수평 위치 설정(화면 밖으로 이동할 수 없음)"
L["Vertical"] = "세로"
L["Set vertical position as percentage of overall height (cannot move beyond edge of display)."] = "전체 너비에 대한 비율로 수직 위치 설정(화면 밖으로 이동할 수 없음)"
L["Bar/Icon Limit"] = "바/아이콘 제한"
L["Set the maximum number of bars to display (bars that sort closest to the anchor have priority). If this is set to 0 then the number of bars is not limited."] = "바에 표시할 최대 수 설정 (bars that sort closest to the anchor have priority). 이것을 0으로 설정하면 바의 수는 무제한임"
L["Attachment"] = "부착"
L["Select a bar group to attach to (for independent position, attach to self)."] = "부착할 바 그룹 선택 (자신에가 부착하면 위치는 독립적이 됨)"
L["Offset X"] = true
L["Set horizontal offset from the selected bar group."] = "선택된 바 그룹으로 부터 수평 위치 설정"
L["Offset Y"] = true
L["Set vertical offset from the selected bar group."] = "선택된 바 그룹으로 부터 수직 위치 설정"
L["Last Bar"] = "마지막 바"
L["If checked, position is relative to last bar/icon in the selected bar group."] = "선택시, 위치는 선택된 바 그룹의 마지막 바에 상대적임"
L["Empty"] = "빈"
L["By Row"] = "행으로"
L["When wrap is enabled in the selected bar group, position is relative to last bar/icon in row closest to the anchor."] = "포장이 선택한 바 그룹에 활성화된 경우, 위치는 앵커에 가까운 연속으로 마지막으로 바 / 아이콘 관련이 있습니다."
L["By Column"] = "열을 기준으로"
L["When wrap is enabled in the selected bar group, position is relative to last bar/icon in column closest to the anchor."] = "포장이 선택한 바 그룹에 활성화된 경우, 위치는 앵커에 가까운 열의 마지막 바 / 아이콘 관련이 있습니다."
L["Parent Frame"] = "부모 프레임"
L["Enter name of parent frame for this bar group (leave blank to use default)."] = true
L["Anchor Frame"] = "고정 프레임"
L["Enter name of anchor frame to attach to (leave blank to enable bar group attachment)."] = true
L["Anchor Point"] = "고정 포인트"
L["Select point on anchor frame to attach to."] = true
L["Reset attachment options."] = true
L["Frame Stack"] = "프레임 쌓기"
L["Toggle showing Blizzard's frame stack tooltips."] = true

-- Bar Groups > Appearance tab
L["Appearance"] = "외형"
L["Use Defaults"] = "기본값 사용"
L["If checked, fonts and textures use the default values."] = "선택시, 글꼴 및 질감을 기본값으로 사용"
L["Restore Defaults"] = "기본값 복원"
L["Reset fonts and textures for this bar group back to the current defaults."] = "이 바 그룹의 글꼴 및 질감을 기본값으로 복원"
L["Copy From"] = "(으)로부터 복사"
L["Select bar group to copy font and texture settings from."] = "선택된 바그룹의 글꼴 및 질감 복사"
L["If checked, colors use the default values."] = "선택시, 색상을 기본값으로 사용"
L["Reset standard colors for this bar group back to the current defaults."] = "이 바 그룹의 표준 색상을 기본값으로 설정"
L["Select bar group to copy standard colors from."] = "선택된 바그룹으로부터 표준 색상 복사"
L["Bar Color Scheme"] = "바 색상 구성표"
L["Foreground:"] = "전경:"
L["Show bars in default colors for their type, including special debuff colors when applicable."] = true
L["Color the bars with a custom color."] = "사용자 정의 색상을 바의 색상으로 사용"
L["Class Colors"] = "직업 색상"
L["Show bars in class colors of associated spells when possible, otherwise use default bar colors."] = "직업과 관련된 주문이면 직업색상으로 보기, 그렇지 않으면 기본 바 색상 사용"
L["Spell Colors"] = "주문 색상"
L["Show bars using spell colors when possible, otherwise use default bar colors."] = "주문 색상을 사용하여 보기, 그렇지 않으면 기본 바 색상 사용"
L["Background:"] = "배경:"
L["Same as Foreground"] = "전경과 같게"
L["Color the background the same as the foreground."] = "배경 색상을 전경과 동일하게 사용"
L["Color the background with a custom color."] = "사용자 정의 색상을 배경 색상으로 사용"
L["Icon Border:"] = "아이콘 테두리:"
L["Color the icon border the same as the bar foreground."] = "아이콘 테두리를 전경과 동일하게 사용"
L["Color the icon border with a custom color."] = "사용자 정의 색상을 아이콘 테두리 색상으로 사용"
L["Color the icon border string"] = "디버프 색상을 아이콘 테두리 색상으로 사용 (예, 마법, 질병, 독, 저주)."
L["None"] = "없음"
L["Do not color the icon border."] = "아이콘 테두리 색상 없음"

-- Bar Groups > Timer Options tab
L["Timer Options"] = "타이머 옵션"
L["Show With Uniform Duration"] = "균일한 지속시간 보기"
L["Show timer bars scaled with a uniform duration (text still shows actual time left)."] = "타이머 바의 지속시간을 균일하게 보기 (문자는 여전히 남은 시간으로 보임)"
L["Enter minutes in the uniform duration."] = "균일한 지속시간의 \"분\" 입력"
L["Enter seconds in the uniform duration."] = "균일한 지속시간의 \"초\" 입력"
L["Show If Unlimited Duration"] = "시간이 무제한인 것만 보기"
L["Show bars for actions with unlimited duration (e.g., paladin auras)."] = "전체시간이 무제한인 행동을 바에 표시 (즉, 성기사 오라)"
L["Only Show Unlimited"] = "무제한인 것만 보기"
L["Show bars for actions only if they have unlimited duration."] = "지속시간이 무제한인 행동만 바에 표시"
L["Full Bars"] = "전체 바"
L["If checked, bars with unlimited duration show as full bars, otherwise they show as empty bars."] = true
L["Unlimited As Zero"] = "제로 일때 무제한"
L["If checked, bars with unlimited duration sort as zero duration, otherwise as very long duration."] = true
L["Check Overall Duration"] = "전체 시간 확인"
L["Only include timer bars with a specified minimum (or maximum) duration."] = true
L["Enter minutes for overall duration check."] = true
L["Enter seconds for overall duration check."] = true
L["Check Time Left"] = "남은 시간 확인"
L["Only show timer bars with a specified minimum (or maximum) time left."] = true
L["Enter minutes for time left check."] = true
L["Enter seconds for time left check."] = true
L["Time Format"] = "시간 형식"
L["Time format string"] = "Select time format for bars and icons. There are separate settings for five ranges: " ..
	"more then an hour, 2 minutes to an hour, 1 minute to 2 minutes, 10 seconds to 1 minute, less than 10 seconds. " ..
	"These are illustrated by samples in the drop-down menu for each format option."
L["Spaces"] = "공백"
L["Include spaces between values in time format."] = true
L["Uppercase"] = "대문자"
L["If checked, use uppercase H, M and S in time format, otherwise use lowercase."] = true
L["Special Effects"] = "특수 효과"
L["Pulse At Start"] = "시작시 확대"
L["Enable icon pulse when bar is started."] = "바 시작시 아이콘 확대 활성화"
L["Pulse When Expiring"] = "종료시 확대"
L["Enable icon pulse when bar is expiring."] = "바 종료시 아이콘 확대 활성화"
L["Hide After Start"] = "시작 후 숨김"
L["Enable hide after start for timer bars (does not hide bars with unlimited duration)."] = "타이머 바 시작 후 숨김 활성화 (지속시간이 무제한이면 숨길 수 없음)"
L["Fade After Start"] = "시작 후 희미함"
L["Enable fade after start (i.e., switch to fade opacity after a delay)."] = "시작 후 희미하게 활성화 (즉, 지연 시간 후 희미함 투명도 적용)"
L["Delay"] = "지연 시간"
L["Set number of seconds before bar will hide or fade."] = "바가 숨김 또는 희미하게 되기 전의 시간 설정"
L["Flash When Expiring"] = "종료전 깜빡임"
L["Enable flashing of expiring bars."] = "바의 종료전 깜빡임 활성화"
L["Flash Time"] = "깜빡임 시간"
L["Set number of seconds before expiration that bar should start flashing."] = "바가 종료 전 깜빡일 시간 설정"

-- Conditions tab
L["Conditions"]= "조건"
L["Condition"] = "조건"
L["New Condition"] = "새 조건"
L["Create a new condition."] = "새 조건 만들기"
L["Enter Condition Name"] = "조건 이름 입력"
L["Enter name of new condition."] = "새 조건 이름 입력"
L["Cancel creating a new condition."] = "새 조건 만들기 취소"
L["Delete Condition"] = "조건 삭제"
L["Delete the selected condition."] = "선택 조건 삭제"
L["Delete condition string"] = function(name) string.format('DELETE CONDITION\nAre you sure you want to delete the "%s" condition?', name) end

-- Conditions > General tab
L["Enable Condition"] = "조건 활성화"
L["If checked, the condition is enabled and its value is determined by evaluating the associated tests, otherwise the condition is disabled and its value is always false."] = true
L["Notification"] = "알림"
L["If checked, this condition is suitable for a notification and will show up as an option for new notify bars."] = true
L["Detailed Tooltip"] = "상세 툴팁"
L["If checked, tooltip for notifications based on this condition will include a detailed description."] = true
L["Share Condition"] = "조건 공유"
L["If checked, this condition's settings can be copied between characters."] = true
L["Copy Condition Settings From"] = "(으)로부터 조건 설정 복사"
L["Select a shared condition to copy settings from, including tests, associated spells, and dependencies."] = true
L["Reset and delete all current shared condition settings."] = true
L["Rename Condition"] = "조건 새이름"
L["Enter new name for the condition."] = true
L["Associated Spell"] = "관련 주문"
L["Enter spell name (or numeric identifier) whose color and icon can be used by notification bars based on this condition."] = true

-- Conditions > Tests tab
L["Tests"] = "검사"
L["Summary"] = "개요"

-- Conditions > Tests > Player Status
L["Enable Test"] = "활성화 검사"
L["Enable"] = "활성화"
L["If checked, enable this test."] = true
L["Combat"] = "전투"
L["If checked, test combat status."] = true
L["If checked, must be in combat."] = true
L["If checked, must be out of combat."] = true
L["Resting"] = "휴식"
L["If checked, test if the player is resting."] = true
L["If checked, player must be resting (e.g., in an inn)."] = true
L["If checked, player must not be resting."] = true
L["Mounted"] = "탈것"
L["If checked, test if the player is mounted."] = true
L["If checked, player must be mounted."] = true
L["If checked, player must not be mounted."] = true
L["Stealthed"] = "은신"
L["If checked, test if the player is stealthed."] = true
L["If checked, player must be stealthed."] = true
L["If checked, player must not be stealthed."] = true
L["Fishing"] = "낚시중"
L["If checked, test if the player is fishing."] = true
L["If checked, player must be ready to fish (i.e., trained with fishing pole equipped)."] = true
L["If checked, player must not be ready to fish."] = true
L["PvP"] = true
L["If checked, test if the player has PvP enabled."] = true
L["If checked, player must have PvP enabled."] = true
L["If checked, player must not have PvP enabled."] = true
L["If checked, test if player is in a party."] = true
L["If checked, player must be in a party."] = true
L["If checked, player must not be in a party."] = true
L["If checked, test if player is in raid group."] = true
L["If checked, player must be in a raid group."] = true
L["If checked, player must not be in a raid group."] = true
L["If checked, test if player is in either a party or raid with other players."] = true
L["If checked, player must be in either a party or raid with other players."] = true
L["If checked, player must not be in either a party or raid with other players."] = true
L["If checked, test if player is in a 5-man or raid instance."] = true
L["If checked, player must be in a 5-man or raid instance."] = true
L["If checked, player must not be in a 5-man or raid instance."] = true
L["If checked, test if player is in an arena."] = "선택시, 플레이어가 투기장에 있을 때 테스트"
L["If checked, player must be in an arena."] = "선택시, 플레이어가 투기장에 반드시 있어야한다"
L["If checked, player must not be in an arena."] = "선택시, 플레이어가 투기장에 반드시 없어야한다"
L["If checked, test if player is in a battleground."] = true
L["If checked, player must be in a battleground."] = true
L["If checked, player must not be in a battleground."] = true
L["If checked, test if the player has a pet."] = true
L["If checked, player must have a pet."] = true
L["If checked, player must not have a pet"] = true
L["Player"] = "플레이어"
L["Pet"] = "소환수"
L["Level"] = "레벨"
L["If checked, test the player's level."] = true
L["If checked, player must be at least at this level, otherwise must be lower."] = true
L["If checked, test the player's health."] = true
L["If checked, player's health must be at least this percentage, otherwise must be less."] = true
L["If checked, test the player's power (i.e., mana, rage, energy, focus, runic power)."] = true
L["If checked, player's power must be at least this percentage, otherwise must be less."] = true
L["If checked, test the player's holy power."] = true
L["If checked, player's holy power must be at least this many charges, otherwise must be less."] = true
L["If checked, test the player's number of soul shards."] = true
L["If checked, player's holy power must be at least this many charges, otherwise must be less."] = true
L["If checked, test the player's eclipse power. You can set power level (-100 to -1 for lunar power, 1 to 100 for solar power) and the comparison to use (either less or greater than the power level)."] = true
L["If checked, player's eclipse power must be at least this level, otherwise must be less."] = true
L["If checked, test the player's eclipse status. You can test current eclipse direction (toward sun or moon) and whether lunar or solar eclipse is active."] = true
L["If checked, player must be in Solar Eclipse."] = "선택시, 플레이어가 일식이어야 합니다"
L["If checked, player must be in Lunar Eclipse."] = "선택시, 플레이어가 월식이어야 합니다"
L["If checked, eclipse direction must be going toward the sun."] = "선택시, 일/월식 방향이 해로 향해야 합니다"
L["If checked, eclipse direction must be going toward the moon."] = "선택시, 일/월식 방향이 달로 향해야 합니다"
L["Available"] = "사용 가능"
L["If checked, test the player's rune status."] = true
L["Any"] = "특정"
L["If checked, at least one rune of any type must be available."] = true
L["If checked, must have at least one blood rune available (or enough death runes)."] = true
L["If checked, must have at least one frost rune available (or enough death runes)."] = true
L["If checked, must have at least one unholy rune available (or enough death runes)."] = true
L["Recharging"] = "재충전"
L["Not Recharging"] = "재충전 아님"
L[">= 1"] = true
L["If checked, test blood runes."] = true
L["If checked, at least one blood rune must be recharging, otherwise none."] = true
L["If checked, test frost runes."] = true
L["If checked, at least one frost rune must be recharging, otherwise none."] = true
L["If checked, test unholy runes."] = true
L["If checked, at least one unholy rune must be recharging, otherwise none."] = true
L["If checked, test how many combo points the player has on the target."] = true
L["If checked, player must have at least this many combo points, otherwise must be fewer."] = true
L["If checked, test the player's totem status."] = true
L["If checked, must have an active totem of this type (or specific totem if Totem Name is defined)."] = true
L["If checked, must not have an active totem of this type (or specific totem if Totem Name is defined)."] = true
L["Totem Name"] = true
L["Enter name of specific totem to check is active."] = true
L["Health"] = "생명력"
L["Power"] = "힘"
L["Minimum"] = "최소한"
L["Holy Power"] = "신성한 힘"
L["Soul Shards"] = "영혼의 조각"
L["Eclipse Power"] = "일/월식 힘"
L["Eclipse State"] = "일/월식 상태"
L["Eclipse"] = "일식"
L["Solar"] = "일"
L["Lunar"] = "월"
L[">> Sun"] = ">> 해"
L[">> Moon"] = ">> 달"
L["Combo Points"] = "연계 점수"
L["If checked, test if the player has a mainhand weapon equipped with at least the specified item level."] = true
L["If checked, test if the player has an offhand weapon equipped with at least the specified item level."] = true
L["If checked, test if the player has an ranged weapon equipped with at least the specified item level."] = true
L["If checked, test if the player is in a stance."] = true
L['Enter the stance to check for (enter "none" to check for no stance).'] = true
L["If checked, test if points have been spent in one of the player's talents."] = true
L["Weapons"] = "무기"
L["Mainhand"] = "주장비"
L["Offhand"] = "보조장비"
L["Ranged"] = "원거리 장비"
L["Stance"] = "태세"
L["Talent"] = "특성"

-- Conditions > Tests > Pet Status
L["Pet Status"] = "소환수 상태"
L["If checked, test if pet currently exists."] = true
L["If checked, pet must exist."] = true
L["If checked, pet must not exist."] = true
L["If checked, test pet's target."] = true
L["No Target"] = true
L["If checked, must not have a target."] = true
L["Player's Target"] = true
L["If checked, must be same as player's target."] = true
L["Any Target"] = true
L["If checked, must have a target."] = true
L["If checked, test the pet's health."] = true
L["If checked, pet's health must be at least this percentage, otherwise must be less."] = true
L["If checked, test the pet's power (i.e., mana, rage, energy, focus)."] = true
L["If checked, pet's power must be at least this percentage, otherwise must be less."] = true

-- Conditions > Tests > Target Status
L["If checked, test if target currently exists."] = true
L["If checked, target must exist."] = true
L["If checked, target must not exist."] = true
L["Player"] = "플레이어"
L["If checked, test if the target is a player."] = true
L["If checked, target must be a player."] = true
L["If checked, target must not be a player."] = true
L["Enemy"] = "적"
L["If checked, test if the target is an enemy."] = true
L["If checked, target must be an enemy."] = true
L["If checked, target must not be an enemy."] = true
L["Friendly"] = "우호적"
L["If checked, test if the target is friendly."] = true
L["If checked, target must be friendly."] = true
L["If checked, target must not be friendly."] = true
L["Dead"] = "사망"
L["If checked, test if the target is dead."] = true
L["If checked, target must be dead."] = true
L["If checked, target must not be dead."] = true
L["Classification"] = "분류"
L["If checked, test the target's classification (you can select multiple classifications)."] = true
L["If checked, test for normal classification."] = true
L["If checked, test for boss classification."] = true
L["If checked, test for elite classification."] = true
L["If checked, test for rare classification."] = true
L["If checked, test for rare elite classification."] = true
L["Range"] = "사정거리"
L["If checked, test if the target is in range."] = true
L["If checked, target must be in range."] = true
L["If checked, target must not be in range."] = true
L["Spellsteal"] = "마법훔치기"
L["Not Spellsteal"] = "마법훔치기 중 아님"
L["If checked, test for a buff that can be transferred to the player with Spellsteal."] = true
L["If checked, there must be a spellstealable buff."] = true
L["If checked, there must not be a spellstealable buff."] = true
L["If checked, test the target's health."] = "선택시, 대상의 생명력 검사"
L["If checked, target's health must be at least this percentage, otherwise must be less."] = true
L["If checked, test the target's power (i.e., mana, rage, energy, focus, runic power)."] = "선택시, 대상의 힘 검사 (예, 마나, 분노, 기력, 룬마력)"
L["If checked, target's power must be at least this percentage, otherwise must be less."] = true

-- Conditions > Tests > Focus Status
L["If checked, test if focus currently exists."] = true
L["If checked, focus must exist."] = true
L["If checked, focus must not exist."] = true
L["If checked, test if the focus is a player."] = true
L["If checked, focus must be a player."] = true
L["If checked, focus must not be a player."] = true
L["If checked, test if the focus is an enemy."] = true
L["If checked, focus must be an enemy."] = true
L["If checked, focus must not be an enemy."] = true
L["If checked, test if the focus is friendly."] = true
L["If checked, focus must be friendly."] = true
L["If checked, focus must not be friendly."] = true
L["If checked, test if the focus is dead."] = true
L["If checked, focus must be dead."] = true
L["If checked, focus must not be dead."] = true
L["If checked, test the focus's classification (you can select multiple classifications)."] = true
L["If checked, test if the focus is in range."] = true
L["If checked, focus must be in range."] = true
L["If checked, focus must not be in range."] = true
L["If checked, test the focus's health."] = true
L["If checked, focus's health must be at least this percentage, otherwise must be less."] = true
L["If checked, test the focus's power (i.e., mana, rage, energy, focus, runic power)."] = true
L["If checked, focus's power must be at least this percentage, otherwise must be less."] = true

-- Conditions > Tests > All Buffs
L["Buff List Entry"] = "버프 목록 항목"
L["Test Buffs"] = "버프 검사"
L["Who Has Buff"] = "버프 대상"
L["Who Cast Buff"] = "버프 시전자"
L["Enter comma-separated list of buffs."] = "쉼표(,)로 구분된 버프 목록을 입력"
L["If checked, test if all the buffs are active."] = true
L["If checked, test if any of the buffs are not active."] = true
L["If checked, test if player buffs."] = true
L["If checked, test if target buffs."] = true
L["If checked, test if focus buffs."] = true
L["If checked, test if the buffs were cast by the player."] = true
L["If checked, test if the buffs were cast by anyone other than the player."] = true
L["If checked, buffs may be cast by anyone, including the player."] = true
L["On Player"] = "플레이어에"
L["On Target"] = "대상에"
L["On Focus"] = "주시대상에"
L["Cast By Target"] = "대상이 시전"
L["Cast By Focus"] = "주시대상이 시전"

-- Conditions > Tests > Any Buffs
L["If checked, test if any of the buffs are active."] = true
L["If checked, test if none of the buffs are active."] = true

-- Conditions > Tests > Buff Time Left
L["Buff Entry"] = "버프 항목"
L["Enter the buff to be tested."] = true
L["Minutes"] = "분"
L["Seconds"] = "초"
L["If checked, test if buff is on player."] = true
L["If checked, test if buff is on pet."] = true
L["If checked, test if buff is on target."] = true
L["If checked, test if buff is on focus."] = true
L["If checked, test if the buff was cast by the player."] = true
L["If checked, test if the buff was cast by anyone other than the player."] = true
L["If checked, buff may be cast by anyone, including the player."] = true

-- Conditions > Tests > Buff Count
L["Enter buff to test for stack count (if buff doesn't stack then its count is 0)."] = true
L["Stack Count"] = "중첩 갯수"
L["Enter value to compare with the buff stack count."] = true
L["Comparison"] = "비교"

-- Conditions > Tests > Buff Type
L["Player Has Buff"] = "플레이어가 가진 버프"
L["If checked, player must have a mainhand buff."] = true
L["If checked, player must have an offhand buff."] = true
L["If checked, player must have a ranged buff."] = true
L["If checked, true if player has a buff of the specified type."] = true
L["If checked, true if player does not have a buff of the specified type."] = true
L["Result"] = "결과"

-- Conditions > Tests > All Debuffs
L["Debuff List Entry"] = "디버프 목록 항목"
L["Test Debuffs"] = "디버프 목록"
L["Who Has Debuff"] = "디버프 대상"
L["Who Cast Debuff"] = "디버프 시전자"
L["Enter comma-separated list of debuffs."] = "쉼표(,)로 구분된 디버프 목록을 입력"
L["If checked, test if all the debuffs are active."] = true
L["If checked, test if any of the debuffs are not active."] = true
L["If checked, test if debuff is on player."] = true
L["If checked, test if debuff is on pet."] = true
L["If checked, test if debuff is on target."] = true
L["If checked, test if debuff is on focus."] = true
L["If checked, test if the debuffs were cast by the player."] = true
L["If checked, test if the debuffs were cast by anyone other than the player."] = true
L["If checked, debuffs may be cast by anyone, including the player."] = true

-- Conditions > Tests > Any Debuffs
L["If checked, test if any of the debuffs are active."] = true
L["If checked, test if none of the debuffs are active."] = true

-- Conditions > Tests > Debuff Time Left
L["Enter the debuff to be tested."] = true
L["Debuff Entry"] = "디버프 항목"
L["If checked, test if the debuff was cast by the player."] = true
L["If checked, test if the debuff was cast by anyone other than the player."] = true
L["If checked, debuff may be cast by anyone, including the player."] = true

-- Conditions > Tests > Debuff Count
L["Enter debuff to test for stack count (if debuff doesn't stack then its count is 0)."] = true
L["Enter value to compare with the debuff stack count."] = true

-- Conditions > Tests > Debuff Type
L["Player Has Debuff"] = "플레이어가 가진 디버프"
L["If checked, player must have a poison debuff."] = "선택시, 플레이어는 독 디버프를 가져야 합니다"
L["If checked, player must have a disease debuff."] = "선택시, 플레이어는 질병 디버프를 가져야 합니다"
L["If checked, player must have a curse debuff."] = "선택시, 플레이어는 저주 디버프를 가져야 합니다"
L["If checked, player must have a magic debuff."] = "선택시, 플레이어는 마법 디버프를 가져야 합니다"
L["If checked, true if player has a debuff of the specified type."] = true
L["If checked, true if player does not have a debuff of the specified type."] = true

-- Conditions > Tests > All Cooldowns
L["Spell List Entry"] = "주문 목록 항목"
L["If checked, test if spells are usable (i.e., enough mana, reagents, etc.)."] = true
L["Enter comma-separated list of spells."] = "쉼표(,)로 구분된 주문 목록을 입력"
L["Enter seconds for cooldown time left check."] = true

-- Conditions > Tests > Spell Ready
L["Spell Entry"] = "주문 항목"
L["Spell"] = "주문"
L["Enter spell to test if ready to be cast."] = true
L["If checked, test if spell is on global cooldown, otherwise ignore global cooldown."] = true
L["Is Usable"] = "사용 가능"
L["If checked, test if spell is usable (i.e., enough mana, reagents, etc.)."] = "선택시, 주문이 사용 가능할 경우 검사 (예, 충분한 마나, reagents, 기타)"
L["If checked, also test if the target is in range of the spell."] = "선택시, 대상이 주문의 사정거리 안에 있는 경우에도 검사"
L["If checked, target must be in range."] = "선택시, 대상은 사정거리 안이어야 합니다"
L["If checked, target must be out of range."] = "선택시, 대상은 사정거리 밖이어야 합니다"

-- Conditions > Tests > Spell Casting
L["Enter spell to test if being cast or channeled."] = true
L["Who Is Casting"] = "누가 시전한"
L["If checked, test player casting."] = "선택시, 플레이어가 시전한 주문 검사"
L["If checked, test target casting."] = "선택시, 대상이 시전한 주문 검사" 
L["If checked, test focus casting."] = "선택시, 주시대상이 시전한 주문 검사"

-- Conditions > Tests > Item Ready
L["Item Entry"] = "아이템 항목"
L["Item"] = "아이템"
L["Enter name or itemID of item to test. Item must be in the player's bags. Use generic cooldown names for Potions and Elixirs."] = "검사할 이름이나 아이템ID 입력. 아이템은 플레이어의 가방에 있어야 합니다. 물약과 비약에 대한 일반적 쿨다운 이름을 사용"
L["Ready"] = "준비"
L["If checked, test if the item is ready to use."] = true
L["If checked, item must be ready."] = "선택시, 아이템이 준비되어야 합니다"
L["If checked, item must not be ready."] = "선택시, 아이템이 준비되지 않아야 합니다"
L["If checked, test item count."] = true
L["Enter value to compare with item count."] = true
L["Charges"] = true
L["If checked, test the number of charges on the item(s)."] = true
L["Enter value to compare with the number of charges."] = true

-- Conditions > Tests > Result
L["Dependencies"] = true
L["Dependencies string"] = "Dependencies are other conditions that must evaluate to specific results for this condition's result to be true. " ..
	"Dependencies are grouped either with a logical \"And\" (all \"And\" dependencies must evaluate to their specified results) " ..
	"or logical \"Or\" (at least one \"Or\" dependency must evaluate to its specified result). " ..
	"Note that all other tests are evaluated for all conditions before checking dependencies.\n"
L["True"] = "참"
L["Condition is true only if the selected condition evaluates to true."] = "선택된 조건이 참으로 확인될 경우에만 조건이 참임"
L["False"] = "거짓"
L["Condition is true only if the selected condition evaluates to false."] = "선택된 조건이 거짓으로 확인될 경우에만 조건이 참임"
L["And/Or"] = "및/또는"
L["And"] = "및"
L["Or"] = "또는"
L["Toggle between logical \"And\" and \"Or\" for this dependecy."] = true
L["Delete"] = "삭제"
L["Delete this condition from the dependencies list."] = true
L["Test Evaluation"] = "테스트 평가"
L["If checked, evaluate all enabled tests with logical \"And\" (i.e., all tests must be true), othewise use logical \"Or\" (i.e., only one test must be true)."] = '선택하면, 논리\모든 활성화된 시험 평가 "그리고 \"(모든 시험이 사실이어야함), othewise 사용하는 논리적인 \ "또는 \"(즉, 하나의 테스트에 해당되어야함.)'
L["Toggle Result"] = true
L["If checked, the result for this condition, after evaluating all tests and checking dependencies, is toggled."] = true
L["Set Result"] = "결과 설정"
L["If checked, the result for this condition is set to true or false (this feature is provided to help debug conditions)."] = true
L["If checked, result is set to true."] = "선택시, 결과는 참으로 설정"
L["If checked, result is set to false."] = "선택시, 결과는 거짓으로 설정"

-- In-Combat Buffs tab
L["In-Combat Bar"] = "전투중 버프 취소 바"
L["Enable In-Combat Bar"] = "전투중 버프 취소 바 활성화"
L["In-combat string"] = "Raven 포함 옵션 \"전투중 버프 취소 바\" 전투중에 버프를 취소하는 데 사용할 수 있음. 바의 배치를 구성하고 여기에 나와 있는 옵션을 사용하여 취소할 버프를 선택합니다. 선택된 버프중 하나가 전투중 활성화될 때, 표시줄에 표시된 아이콘에 우클릭으로 버프를 취소할수 있습니다.\n"
L["Enable in-combat buffs string"] = "우클릭으로 전투중 취소할 수 있는 버프 아이콘을 표시할 바를 활성화"
L["Lock Bar Layout"] = "바 배치 잠금"
L["Lock in-combat string"] = "바 배치 앵커 잠금 및 숨김"
L["Link Bar Layout"] = "바 배치 연결"
L["Link in-combat settings string"] = "배치 설정(버프 목록은 아님)을 바 배치 연결이 선택된 모든 프로필에 공유"
L["Out Of Combat"] = "전투 아님"
L["If checked, also display buffs on the bar when out of combat."] = "선택시, 비전투시에도 버프 표시"
L["Enter in-combat buff string"] = "in-combat 목록에 추가할 플레이어 버프 이름 입력"
L["Buff List"] = "버프 목록"
L["Delete the selected buff from the in-combat list."] = "in-combat 목록에 선택된 버프 삭제"
L["Reset the in-combat buff list."] = "in-combat 버프 목록 초기화"
L["Set size for the buff icons."] = "버프 아이콘의 크기 설정"
L["Horizontal Bar"] = "수평바"
L["Configure as a horizontal bar of buff icons."] = "버프 아이콘을 수평바로 구성"
L["Vertical Bar"] = "수직바"
L["Configure as a vertical bar of buff icons."] = "버프 아이콘을 수직바로 구성"
L["Spacing"] = "간격"
L["Set spacing between the buff icons."] = "버프 아이콘 사이의 간격 설정"
L["Set scale factor for the bar."] = "바의 스케일 설정"
L["Set opacity for the bar."] = "바의 투명도 설정"
L["Mainhand Weapon"] = "주장비"
L["Offhand Weapon"] = "보조장비"
L["Ranged Weapon"] = "원거리 장비"
L["Enter name of anchor frame to attach to (leave blank to enable manual positioning)."] = true

-- Highlights tab
L["Highlights"] = "하이라이트"
L["Highlights string"] = "Bartender4, Dominos 또는 Macaroon을 사용하면 버튼 하이라이트를 활성화 할 수 있습니다 " ..
	"to indicate active buffs and debuffs that you cast (with flashing to indicate they are expiring). " ..
	"One highlight can be shown at a time and the priority is those on target first, focus second, and player last. " ..
	"You can also show cooldown counters on buttons for spells and items (disabled by default if OmniCC is loaded).\n"
L["Enable Highlights"] = "하이라이트 활성화"
L["If checked, enable Raven's support for button highlights and cooldown counts."] = true
L["Use ButtonFacade"] = "버튼 외형 사용"
L["Enable setting highlights through ButtonFacade if it is loaded. This is not ideal for every BF skin which is why it can be disabled. Try both enabled and disabled settings and see which works best."] = true
L["Highlight Buffs"] = "하이라이트 버프"
L["Enable player buff highlights on buttons."] = true
L["Buff Color"] = "버프 색상"
L["Set player buff highlight color."] = true
L["Highlight Debuffs"] = "하이라이트 디버프"
L["Enable player debuff highlights on buttons."] = true
L["Debuff Color"] = "디버프 색상"
L["Set player debuff highlight color."] = true
L["Enable target buff highlights on buttons."] = true
L["Set target buff highlight color."] = true
L["Enable target debuff highlights on buttons."] = true
L["Set target debuff highlight color."] = true
L["Enable focus buff highlights on buttons."] = true
L["Set focus buff highlight color."] = true
L["Enable focus debuff highlights on buttons."] = true
L["Set focus debuff highlight color."] = true
L["Flashing"] = "낚시중"
L["Enable highlight flashing for expiring buffs and debuffs."] = true
L["Set number of seconds to flash before buffs and debuffs expire."] = true
L["Cooldown Time"] = "쿨다운 시간"
L["Show cooldown time remaining on buttons."] = true
L["Set font size for cooldown time text overlay."] = "쿨다운 문자에 입힐 글꼴 크기 설정"
L["Font"] = "글꼴"
L["Select font for cooldown time text overlay."] = "쿨다운 문자에 입힐 글꼴 선택"
L["Cooldown format string"] = "Select time format for bars and icons. There are separate settings for five ranges: " ..
	"more then an hour, 2 minutes to an hour, 1 minute to 2 minutes, 10 seconds to 1 minute, less than 10 seconds. " ..
	"These are illustrated by samples in the drop-down menu for each format option."
L["Alignment"] = "정렬"
L["Vertical:"] = "수직:"
L["Horizontal:"] = "수평:"
L["If checked, vertically align cooldown text to top."] = "선택시, 쿨다운 문자 하단에 수직 정렬"
L["If checked, vertically align cooldown text in middle."] = "선택시, 쿨다운 문자 중간에 수직 정렬"
L["If checked, vertically align cooldown text to bottom."] = "선택시, 쿨다운 문자 하단에 수직 정렬"
L["If checked, horizontally align cooldown text to left."] = "선택시, 쿨다운 문자 좌측에 수평 정렬"
L["If checked, horizontally align cooldown text in center."] = "선택시, 쿨다운 문자 중심에 수평 정렬"
L["If checked, horizontally align cooldown text to right."] = "선택시, 쿨다운 문자 우측에 수평 정렬"

-- Inserted Bar Information tab
L["Bar Information"] = "바 정보"
L["Custom Sort Order"] = "사용자 정의 정렬 순서"
L["Move Up"] = "위로 이동"
L["Move the bar up, overriding sort order."] = "정렬 순서를 무시하고 바를 위로 이동"
L["Move Down"] = "아래로 이동"
L["Move the bar down, overriding sort order."] = "정렬 순서를 무시하고 바를 아래로 이동"
L["If checked, enable showing the bar."] = "선택시, 바 보기 활성화"
L["Enter label text for the bar."] = "바의 라벨 문자 입력"
L["Label Link"] = "라벨 연결"
L["If checked, label is linked to the associated spell and changing it here will change it for all bars linked to the same spell."] = true
L["Show When Ready"] = "준비되면 표시"
L["If checked, show ready bar when action is not on cooldown."] = "선택시, 쿨다운이 돌아온 행동을 바에 표시"
L["Show Not Active"] = "활성화되지 않을 때 표시"
L["If checked, show ready bar when action is not active."] = "선택시, 활성화되지 않은 행동을 바에 표시"
L["Usable"] = "사용 가능"
L["If checked, show ready bar only if spell is usable (i.e., enough mana, reagents, etc.)."] = "선택시, 사용가능한 주문을 바에 표시(예, 충분한 마나, reagents, 기타.)"
L["Show Time"] = "시간 보기"
L["Set number of seconds to show the ready bar (0 for unlimited time)."] = "준비된 바에 볼 초 숫자 설정(0은 무제한 시간)"
L["Color and Icon"] = "색상과 아이콘"
L["Use Spell Color"] = "주문 색상 사용"
L["If checked, use color from associated spell."] = "선택시, 관련 주문의 색상 사용"
L["Use Spell Icon"] = "주문 아이콘 사용"
L["If checked, use icon from associated spell."] = "선택시, 관련 주문의 아이콘 사용"
L["Color Link"] = "색상 연결"
L["If checked, the color is linked to the associated spell and changing it here will change it for all bars linked to the same spell."] = true
L["Hide"] = "숨김"
L["If checked, bar is conditionally hidden."] = "선택시, 바를 조건적으로 숨김"
L["If checked, bar is hidden if the condition is true."] = "선택시, 조건이 참이면 바 숨김"
L["If checked, bar is hidden if the condition is false."] = "선택시, 조건이 거짓이면 바 숨김"
L["Hide Condition"] = "숨김 조건"
L["Flash"] = "깜빡임"
L["If checked, bar will conditionally flash."] = "선택시, 바는 조건적으로 깜빡임"
L["If checked, bar will flash if the condition is true."] = "선택시, 조건이 참이면 바 깜빡임"
L["If checked, bar will flash if the condition is false."] = "선택시, 조건이 거짓이면 바 깜빡임"
L["Flash Condition"] = "깜빡임 조건"
L["Fade"] = "희미함"
L["If checked, bar will conditionally change from normal opacity to fade opacity."] = true
L["If checked, bar will fade if the condition is true."] = "선택시, 조건이 참이면 바 희미함"
L["If checked, bar will fade if the condition is false."] = "선택시, 조건이 거짓이면 바 희미함"
L["Fade Condition"] = "희미함 조건"
L["Normal Opacity"] = "일반 투명도"
L["Set normal opacity for this bar."] = "이 바의 일반 투명도를 설정"
L["Fade Opacity"] = "희미함 투명도"
L["Set fade opacity for this bar."] = "이 바의 희미함 투명도 설정"
L["Set opacity for faded bars."] = "희미함바의 투명도 설정"
L["Ready Opacity"] = "투명도 준비"
L["Set opacity for ready bar."] = "준비 바의 투명도 설정"
L["Type"] = "유형"
L["If checked, this is a notify bar."] = "선택시, 이것은 알림바입니다"
L["If checked, this is a buff bar."] = "선택시, 이것은 버프바입니다"
L["If checked, this is a debuff bar."] = "선택시, 이것은 디버프바입니다"
L["If checked, this is a cooldown bar."] = "선택시, 이것은 쿨다운바입니다"
L["Source"] = "소스"
L["Race"] = "종족"
L["If checked, select actions associated with a class."] = "선택시, 직업에 관련된 행동을 선택합니다"
L["If checked, select actions associated with a pet."] = "선택시, 소환수에 관련된 행동을 선택합니다"
L["If checked, select actions associated with a race."] = "선택시, 종족에 관련된 행동을 선택합니다"
L["If checked, enter spell name for an associated action."] = "선택시, 행동에 관련된 주문 이름을 입력합니다"
L["Druid"] = "드루이드"
L["If checked, select druid actions."] = "선택시, 드루이드 행동 선택"
L["Hunter"] = "사냥꾼"
L["If checked, select hunter actions."] = "선택시, 사냥꾼 행동 선택"
L["Mage"] = "마법사"
L["If checked, select mage actions."] = "선택시, 마법사 행동 선택"
L["Paladin"] = "성기사"
L["If checked, select paladin actions."] = "선택시, 성기사 행동 선택"
L["Priest"] = "사제"
L["If checked, select priest actions."] = "선택시, 사제 행동 선택"
L["Rogue"] = "도적"
L["If checked, select rogue actions."] = "선택시, 도적 행동 선택"
L["Shaman"] = "주술사"
L["If checked, select shaman actions."] = "선택시, 주술사 행동 선택"
L["Warlock"] = "흑마법사"
L["If checked, select warlock actions."] = "선택시, 흑마법사 행동 선택"
L["Warrior"] = "전사"
L["If checked, select warrior actions."] = "선택시, 전사 행동 선택"
L["Death Knight"] = "죽음의 기사"
L["If checked, select death knight actions."] = "선택시, 죽음의 기사 행동 선택"
L["Conditions To Monitor"] = "조건 모니터링"
L["Select all the conditions."] = "모든 조건 선택"
L["Deselect all the conditions."] = "모든 조건 해제"
L["Other Spell"] = "다른 주문"
L["Enter spell name (or numeric identifier) to associate with a bar."] = "바와 관련된 주문의 이름 (또는 주문ID)를 입력하십시오."
L["Actions To Monitor"] = "행동 모니터링"
L["All On"] = "모두 선택"
L["Select all the actions."] = "모든 행동 선택"
L["All Off"] = "모두 해제"
L["Deselect all the actions."] = "모든 행동 해제"
L["If checked, must be on the player."] = "선택시, 플레이어의 행동이어야 합니다."
L["If checked, must be on the player's pet."] = "선택시, 플레이어의 소환수의 행동이어야 합니다."
L["If checked, must be on the target."] = "선택시, 대상의 행동이어야 합니다."
L["If checked, must be on the focus."] = "선택시, 주시대상의 행동이어야 합니다."
L["If checked, must be on the mouseover unit."] = "선택시, 마우스오버 대상의 행동이어야 합니다."
L["If checked, must be on the pet's target."] = "선택시, 소환수의 대상의 행동이어야 합니다."
L["If checked, must be on the target's target."] = "선택시, 대상의 대상의 행동이어야 합니다."
L["If checked, must be on the focus's target."] = "선택시, 주시대상의 대상의 행동이어야 합니다."
L["If checked, only track if cast by the player."] = "선택시, 오직 플레이어에 의해 시전된 주문만 추적"
L["If checked, only track if cast by the player's pet."] = "선택시, 오직 플레이어의 소환수에 의해 시전된 주문만 추적"
L["If checked, only track if cast by anyone other than the player."] = "선택시, 오직 플레이어외의 모든사람에 의해 시전된 주문만 추적"
L["If checked, track if cast by anyone, including player and pet."] = "선택시, 모든사람에 의해 시전된 주문 추적"
L["OK"] = "확인"
L["Confirm creating new bars for the selected actions/conditions."] = "선택된 행동/조건에 대한 새로운 바를 생성합니다"
L["Cancel creating new bars."] = "새 바 만들기 취소"

------- New Entries September 5, 2011
L["Enrage"] = "화나게하다"
L["Include enrage debuffs."] = "화나게의 debuffs를 포함합니다."
L["Required Class"] = "필수 클래스"
L["Enter class required for internal cooldown (leave blank if all classes can trigger the internal cooldown)."] = "내부 재사용 대기 시간 (모든 클래스 내부 재사용를 실행할 수없는 경우 공란 처리)에 필요한 클래스를 입력하십시오."
------- New Entries September 6, 2011
L["If checked, hide count overlay text on icon."] = "선택하면, 아이콘 오버레이 텍스트를 포함 숨깁니다."
L["If checked, set \"Left\" alignment for icon text."] = '"확인란을 선택하면 설정 \"왼쪽 \ "아이콘 텍스트의 정렬."'
L["If checked, set \"Center\" alignment for icon text."] = '"확인란을 선택하면 설정 \"센터 \ "아이콘 텍스트의 정렬."'
L["If checked, set \"Right\" alignment for icon text."] = '"확인란을 선택하면 설정이 \"마우스 오른쪽 \ "아이콘 텍스트의 정렬."'
------- New Entries October 1, 2011
L["Castable"] = "캐스터블"
L['Include buffs that the player can cast.'] = '플레이어가 캐스트 수있는 좋아하는 분들을 포함합니다.'
L['Include debuffs that the player can cast.'] = '플레이어가 캐스트 수 debuffs를 포함합니다.'
L["NPC"] = "NPC"
L['Include buffs cast by an NPC (note: only valid while caster is selected, such as when checking target of target).'] = 'NPC에 의해 캐스팅 좋아하는 분들 포함합니다. (주의 : 대상의 대상을 선택하면 같은 캐스터가 선택되는 동안에만 유효를)'
L['Include debuffs cast by an NPC (note: only valid while caster is selected, such as when checking target of target).'] = 'NPC에 의해 캐스팅 debuffs 포함합니다. (주의 : 대상의 대상을 선택하면 같은 캐스터가 선택되는 동안에만 유효를)'
L['Include buffs cast by a vehicle (note: only valid while caster is selected, such as when checking target of target).'] = '차량으로 캐스팅 좋아하는 분들 포함합니다. (주의 : 대상의 대상을 선택하면 같은 캐스터가 선택되는 동안에만 유효를)'
L['Include debuffs cast by a vehicle (note: only valid while caster is selected, such as when checking target of target).'] = '차량으로 캐스팅 debuffs 포함합니다. (주의 : 대상의 대상을 선택하면 같은 캐스터가 선택되는 동안에만 유효를)'
------- New Entries October 26, 2011
L["Icon Color:"] = "아이콘 색상 :"
L["Desaturate Non-Player"] = "비 플레이어 채도감소"
L["Desaturate if action not cast by player."] = "행동이 선수로 캐스팅하지 않을 경우 채도감소te."
------- New Entries October 27, 2011
L["Also Time Left"] = "또한 지난 시간"
L['If checked, before applying selected sort order, first sort by time left.'] = '선택하면, 선택된 정렬 순서를 적용하기 전에,지난 시간으로 먼저 정렬'
L["Also Player First"] = "또한 플레이어 우선"
L['If checked, after applying selected sort order, sort bars with actions by player first.'] = '선택하는 경우, 선택 적용 한 후 정렬 순서, 플레이어에 의해 작업 정렬 바 먼저.'
------- New Entries November 15, 2011
L["Set opacity for bar group when in combat."] = "전투시 바 그룹의 투명도 설정."
L["Set opacity for bar group when out of combat."] = "전투 종료시 바 그룹의 투명도 설정."
L["Set opacity for bar group when mouse is over it (overrides in and out of combat opacities)."] = "바 그룹에 마우스 오버시 투명도 설정(전투가 들락날락해도 투명도 무시)"
L["Fade Effects"] = "사라지는 효과"