-- Presets.lua
-- Auto-generated by tools/generate_cooldown_preset.py
-- Key format: classID * 10 + specIndex (matches CooldownViewer spec tag)
local RealUI_Auras = RealUI_Auras

RealUI_Auras.Presets = {
    -- Warrior (classID=1)
    [11] = "1|a2FZyM24kHshY1OHFANTz0EpBuYqdikGxiVmUgwsDIKSkjMkPZylGBhrtkkxMF3QWcTQgk0ZYwu6woWMKY5FucUA",  -- Arms
    [12] = "1|a2FZyMO4kGchY1OHFAPTBX0pBuY6CykGxiVmkmzbJSVnSHo4SzEw1mwDSeosYmjBVMTYgq5sIWOKW2lRJQA=",  -- Fury
    [13] = "1|a2FZyMu4kHchY1OHJEuHpNF6SeZ0KQbGJWaSkjMkPZylGBhrtknGFixiaEGVZmxBVbCQMSugKL8kNbkkMz8PAA==",  -- Protection

    -- Paladin (classID=2)
    [21] = "1|a2FZKMq4UHQhY1OHZE2SFAOzL7ck4ydJpiYpBsby55LM/ySlZSSZQxcxtKBKM7agKljImOKRn1MJAA==",  -- Holy
    [22] = "1|a2FZKMa4UGwhY1OHZE2PFANjULNkTZYkU5MUA2P5c0nmf5LSMpLMoYsYWlClGVtQFSxkzAooyi9JTS7JzM8DAA==",  -- Protection
    [23] = "1|a2FZKM64UHwhY1OHZE2PFAPz84NSDEwXwySZmqQYGMufSzL/k5SWkWQOXcTQgq6AsQVVyULG7KDUkqLMpNKSzPw8AA==",  -- Retribution

    -- Hunter (classID=3)
    [31] = "1|a2FZKCHPuFBCfiFjU4ekT5kUA9PnX1IMzELXpBgYr6dLMTCuOiDFwHR9phQD010mKQYm+0WLGFowFTK2YFO6kDHXKTWxuETBN7G4JLWoEgA=",  -- Beast Mastery
    [32] = "1|a2FZKKHAuFBCYSFjU4cUA0t6qqT3KykG5h+TpRiY34hIMTCuOiDFwHR9phQD010mKQYm+0WLGFowFTK2YFO6kDHHN7Eouzg3Ma84I7MAAA==",  -- Marksmanship
    [33] = "1|a2FZKKHIuFBCcSFjU4cUA2sTmxQD89eFIMJeioHp+kYpBsZVB0CsmVIMTHeZQIT1IoYWbEoZW7ApXsiYEVxaVJZZlpgDAA==",  -- Survival

    -- Rogue (classID=4)
    [41] = "1|a2FZKKHJuFBCcyFjU4cUA6OpihQDaz2TFAPro2hJdgdJtmeSlT8kReZKcugtYmjBVMDYgqxkIWOuY3FxYnFxZl5iSWZ+HgA=",  -- Assassination
    [42] = "1|a2FZKKHFuFBCayFjU4ek6TYpBpYLJVIMTL8bJdkdJNmeSVb+kBSZK8mht4ihBV2asQVZwULGNP/SkpzEcgA=",  -- Outlaw
    [43] = "1|a2FZKKHNuFBCeyFjU4cUA+OteikGpssPpRhYPPol2R0k2Z5JVv6QFJkryaG3iKEFUwFjC7KShYwZwaVJJTmpJZUA",  -- Subtlety

    -- Priest (classID=5)
    [51] = "1|a2FZKGHMuFDCeCFjU4fkzg2SX2ZJNm6TYmD6flbSpl6SyUuKgVEuV1J+1yKGFlRpxhZUBQsZs1wyi5MzC3Iy81IB",  -- Discipline
    [52] = "1|a2FZKGHCuFDCZCFjU4cUAzPvd8m/3pK71kgxsHB/krSpl2TykmJglMuVlN+1iKEFXQFjC6qShYwpHvk5lQA=",  -- Holy
    [53] = "1|a2FZKGHKuFDCdCFjU4cUA3P1EikGFua/Ugys349KtjVK2tRLMnlJ7nwoKb9rEUMLpgLGFmQlCxnTgjMSU/LLAQ==",  -- Shadow

    -- Death Knight (classID=6)
    [61] = "1|a2FZKGHLuFDCdiFjU4fk/hbJ6welGJh+ykgxMGsES+5cIbnPWXLfDMnjOYsYWtClGVuQFSxkTHXKyc9PAQA=",  -- Blood
    [62] = "1|a2FZKGHHuFDCbiFjU4fkCXcpBhZnNikGpqDrkjsvSO5cIbnPWXLfDMnjOYsYWtClGVuQFSxkTHUryi8uAQA=",  -- Frost
    [63] = "1|a2FZKGHPuFDCfiFjU4cUA4vJZ8llsyQPmEn+8JDcuUJyn7PkvhmSx3MWMbSgSjK2IEsvZEwLzcvIz6kEAA==",  -- Unholy

    -- Shaman (classID=7)
    [71] = "1|a2FZKOHOuFDCfSFjU4cUA9ObSVIMzKzXpRgY9zZJMTC9+yn5qEuKgXHZexDxU/Kk1SKGFmzKGFvQFS5kzHTNSc1NzStJzAEA",  -- Elemental
    [72] = "1|a2FZKOHBuFDCYyFjU4fkSV8pBsa9zVIMzExxUgysdxMkH3VJMTAuew8ifkqetFrE0IKpiLEFXdlCxmzXvIzEvOTU3NS8EgA=",  -- Enhancement
    [73] = "1|a2FZKOHJuFDCcyFjU4cUA+OyH1IMjHU3JO3tpRgY97ZIPuoCCb4HET8lT1otYmjBVMSIoWwhY3ZQanFJflFiSWZ+HgA=",  -- Restoration

    -- Mage (classID=8)
    [81] = "1|a2FZKBHIuFAicCFjU4ekPpcUA+tkNSkGluePpRiYIqQkOaIlN9ZJOEne0FvE0IIpz9iCpGIhY5pjUXJiXioA",  -- Arcane
    [82] = "1|a2FZKBHEuFAiaCFjU4cUA9PzfCkGpvCbUgzM71gl166U5IiW3Fgn4SR5Q28RQwumPGMLkoqFjClumUWpAA==",  -- Fire
    [83] = "1|a2FZKBHMuFAieCFjU4ekwQ4pBkavV1IMzAp3pRiYwn9LckRLbqyTcJK8obeIoQVTnrEFScVCxlS3ovziEgA=",  -- Frost

    -- Warlock (classID=9)
    [91] = "1|a2FZKBHNuFAieiFjU4cUA7NijRQD454jUgxsB9OkGFifb5X02S/FwDjTVYqBcXmDpFTrIoYWbMoYW9AVLmTMckxLy8lMLsnMzwMA",  -- Affliction
    [92] = "1|a2FZKBHDuFAiZiFjU4cUAwv3YykGxq1SUgws7NulGFiEL0r67JdiYJzpKsXAuLxBUqp1EUMLNmWMLegKFzJmuaTm5ufl5+SnVwIA",  -- Demonology
    [93] = "1|a2FZKBHLuFAidiFjU4ckS5IUA+OeQ1IMjJYFUgxMQTqSPvulGBhnukoxMC5vkJRqXcTQgqmIsQVd2ULGbJfU4pKi0uSSzPw8AA==",  -- Destruction

    -- Monk (classID=10)
    [101] = "1|a2FZKJHKuFAidSFjU4cUA+MhZikGJtZHUgyMB19IMbC8Pi3FwHj8oRQD46VQkFibFAPjiZxFDC3YlDKCRDEUL2TMcipKLc9NLC5JLQIA",  -- Brewmaster
    [102] = "1|a2FZKJHGuFAibSFjU4cUA+OhPCkGZg4OKQbGE4VSDCzffKUYGI8/lGJgvBQqxcB4sA0kkbOIoQWbUkaQKIbihYxZvpnFJeWpiWWpRQA=",  -- Mistweaver
    [103] = "1|a2FZKJHOuFAifSFjU4cUA5PkcikGxicMUgxMQblSDIy7f0gxMB5/KMXAeClUioHxYJsUA+OJnEUMLdiUMrZgU7yQMSs8My+lPDEnO7UIAA==",  -- Windwalker

    -- Druid (classID=11)
    [111] = "1|a2FZKJHPuFAifyFjU4cUA9O39VIMzBJCUgzMyi5SDIwTFkgxMC4Ml4yUkSx8J8XAxFq6iKEFmzLGFnSFCxnTnRJzEvOSUwE=",  -- Balance
    [112] = "1|a2FZKFHAuFCiYCFjU4cUA+PC41IMLIZTpRgYJ/RLvp8BEgmXjJSRLHwnxcDEWrqIoQVTESNYDFnZQsZUt9SixBwA",  -- Feral
    [113] = "1|a2FZKFHIuFCicCFjU4fkkXlSDIwT5klGWkm+nyHFwLgwXDJSRrLwnRQDE2vpIoYWVAWMLehKFjJmuJcmFqVkJuYBAA==",  -- Guardian
    [114] = "1|a2FZKFHEuFCiaCFjU4ck0xPJlmQpBsb+Y1IMzCyRUgyMC8MlI2UkC99JMTCxli5iaEFXwtiCrmghY3ZQanFJflFiSWZ+HgA=",  -- Restoration

    -- Demon Hunter (classID=12)
    [121] = "1|a2FZKFHJuFCiciFjU4cUA9Prw1IMzKy1UgzMnzOkGFhXikoxMJ09IcXAzJAnxcDMvleKgWl34SKGFmxKGUGiGIoXMqZ6JJblJwMA",  -- Havoc
    [122] = "1|a2FZKFHFuFCiaiFjU4cUA9PdzVIMzDJfpRiY5U2kGFhXikoxMJ09IcXAzJAHkvgmxcC0u3ARQws2pYwgUQzFCxkzw1Lz0lMT85JTAQ==",  -- Vengeance

    -- Evoker (classID=13)
    [131] = "1|a2FZKNHMuFCieSFjU4cUA+tOfSkG1uIoKQbWqoVSDKzLRaQYWGOypBhYe3ukGFi3+UgxsDamLWJowaaUESSKoXghY7ZLallicUliSWZ+HgA=",  -- Devastation
    [132] = "1|a2FZKNHCuFCiZSFjU4cUA2sPnxQDay2ItVJAioE1L0GKgTUmS4qBtbdHioF1m48UA2tj2iKGFmxKGUGiGIoXMuYEFKUWpxaVJZZk5ucBAA==",  -- Preservation
    [133] = "1|a2FZKNHKuFCidSFjU4cUAxv7BCkGNo31Ugxs3P+kGNjs7ksxsMZkSTGw9vZIMbBu85FiYG1MW8TQgk0pYws2xQsZcxxL03NT80oSSzLz8wA=",  -- Augmentation
}
