name: Pull Request

on: pull_request

jobs:
  pull_request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Run Luacheck
      uses: nebularg/actions-luacheck@d4137dd840545b28521ed21931e06913d93c0bc1 # v1.1.2
      with:
        args: --no-color -q
        annotate: warning
