name: Pull Request

on: pull_request

jobs:
  pull_request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Run Luacheck
      uses: nebularg/actions-luacheck@d4137dd840545b28521ed21931e06913d93c0bc1 # v1.1.2
      with:
        args: --no-color -q
        annotate: warning
